import visa from "./assets/visa.svg";
import mastercard from "./assets/mastercard.svg";
import { Country, Currencies, PhonePrefixes, TransferCountry } from "./types";

const CONTENT_STYLES = {
  sitePaddingX: "200px",

  heights: {
    navBar: "92px",
    heroSection: "500px",
  },
};

const USER_COUNTRIES: Country[] = [
  {
    code: "AT",
    name: { en: "Austria", es: "Austria", pt: "Áustria", fr: "Autriche" },
  },
  {
    code: "AU",
    name: {
      en: "Australia",
      es: "Australia",
      pt: "Austrália",
      fr: "Australie",
    },
  },
  {
    code: "BE",
    name: { en: "Belgium", es: "Bélgica", pt: "Bélgica", fr: "Belgique" },
  },
  {
    code: "CA",
    name: { en: "Canada", es: "Canadá", pt: "Canadá", fr: "Canada" },
  },
  {
    code: "ES",
    name: { en: "Spain", es: "España", pt: "Espanha", fr: "Espagne" },
  },
  {
    code: "CH",
    name: { en: "Switzerland", es: "Suiza", pt: "Suíça", fr: "Suisse" },
  },
  {
    code: "DE",
    name: { en: "Germany", es: "Alemania", pt: "Alemanha", fr: "Allemagne" },
  },
  {
    code: "DK",
    name: { en: "Denmark", es: "Dinamarca", pt: "Dinamarca", fr: "Danemark" },
  },
  {
    code: "FR",
    name: { en: "France", es: "Francia", pt: "França", fr: "France" },
  },
  {
    code: "GB",
    name: {
      en: "United Kingdom",
      es: "Reino Unido",
      pt: "Reino Unido",
      fr: "Royaume-Uni",
    },
  },
  {
    code: "US",
    name: {
      en: "United States",
      es: "Estados Unidos",
      pt: "Estados Unidos",
      fr: "États-Unis",
    },
  },
];

const TRANSFER_COUNTRIES: TransferCountry[] = [
  {
    code: "AD",
    name: { en: "Andorra", es: "Andorra", pt: "Andorra", fr: "Andorre" },
  },
  {
    code: "AE",
    name: {
      en: "United Arab Emirates",
      es: "Emiratos Árabes Unidos",
      pt: "Emirados Árabes Unidos",
      fr: "Émirats arabes unis",
    },
  },
  {
    code: "AF",
    name: {
      en: "Afghanistan",
      es: "Afganistán",
      pt: "Afeganistão",
      fr: "Afghanistan",
    },
  },
  {
    code: "AG",
    name: {
      en: "Antigua and Barbuda",
      es: "Antigua y Barbuda",
      pt: "Antígua e Barbuda",
      fr: "Antigua-et-Barbuda",
    },
  },
  {
    code: "AI",
    name: { en: "Anguilla", es: "Anguila", pt: "Anguilla", fr: "Anguilla" },
  },
  {
    code: "AL",
    name: { en: "Albania", es: "Albania", pt: "Albânia", fr: "Albanie" },
  },
  {
    code: "AM",
    name: { en: "Armenia", es: "Armenia", pt: "Armênia", fr: "Arménie" },
  },
  {
    code: "AN",
    name: {
      en: "Netherlands Antilles",
      es: "Antillas Neerlandesas",
      pt: "Antilhas Holandesas",
      fr: "Antilles néerlandaises",
    },
  },
  {
    code: "AO",
    name: { en: "Angola", es: "Angola", pt: "Angola", fr: "Angola" },
  },
  {
    code: "AR",
    name: {
      en: "Argentina",
      es: "Argentina",
      pt: "Argentina",
      fr: "Argentine",
    },
  },
  {
    code: "AT",
    name: { en: "Austria", es: "Austria", pt: "Áustria", fr: "Autriche" },
  },
  {
    code: "AU",
    name: {
      en: "Australia",
      es: "Australia",
      pt: "Austrália",
      fr: "Australie",
    },
  },
  {
    code: "AW",
    name: { en: "Aruba", es: "Aruba", pt: "Aruba", fr: "Aruba" },
  },
  {
    code: "AZ",
    name: {
      en: "Azerbaijan",
      es: "Azerbaiyán",
      pt: "Azerbaijão",
      fr: "Azerbaïdjan",
    },
  },
  {
    code: "BA",
    name: {
      en: "Bosnia and Herzegovina",
      es: "Bosnia y Herzegovina",
      pt: "Bósnia e Herzegovina",
      fr: "Bosnie-Herzégovine",
    },
  },
  {
    code: "BB",
    name: { en: "Barbados", es: "Barbados", pt: "Barbados", fr: "Barbade" },
  },
  {
    code: "BD",
    name: {
      en: "Bangladesh",
      es: "Bangladés",
      pt: "Bangladesh",
      fr: "Bangladesh",
    },
  },
  {
    code: "BE",
    name: { en: "Belgium", es: "Bélgica", pt: "Bélgica", fr: "Belgique" },
  },
  {
    code: "BF",
    name: {
      en: "Burkina Faso",
      es: "Burkina Faso",
      pt: "Burkina Faso",
      fr: "Burkina Faso",
    },
  },
  {
    code: "BG",
    name: { en: "Bulgaria", es: "Bulgaria", pt: "Bulgária", fr: "Bulgarie" },
  },
  {
    code: "BH",
    name: { en: "Bahrain", es: "Baréin", pt: "Barém", fr: "Bahreïn" },
  },
  {
    code: "BI",
    name: { en: "Burundi", es: "Burundi", pt: "Burundi", fr: "Burundi" },
  },
  {
    code: "BJ",
    name: { en: "Benin", es: "Benín", pt: "Benin", fr: "Bénin" },
  },
  {
    code: "BM",
    name: { en: "Bermuda", es: "Bermudas", pt: "Bermudas", fr: "Bermudes" },
  },
  {
    code: "BN",
    name: { en: "Brunei Darussalam", es: "Brunéi", pt: "Brunei", fr: "Brunéi" },
  },
  {
    code: "BO",
    name: { en: "Bolivia", es: "Bolivia", pt: "Bolívia", fr: "Bolivie" },
  },
  {
    code: "BR",
    name: { en: "Brazil", es: "Brasil", pt: "Brasil", fr: "Brésil" },
  },
  {
    code: "BS",
    name: { en: "Bahamas", es: "Bahamas", pt: "Bahamas", fr: "Bahamas" },
  },
  {
    code: "BT",
    name: { en: "Bhutan", es: "Bután", pt: "Butão", fr: "Bhoutan" },
  },
  // {
  //   code: "BV",
  //   name: {
  //     en: "Bouvet Island",
  //     es: "Isla Bouvet",
  //     pt: "Ilha Bouvet",
  //     fr: "Île Bouvet",
  //   },
  // },
  {
    code: "BW",
    name: { en: "Botswana", es: "Botsuana", pt: "Botsuana", fr: "Botswana" },
  },
  {
    code: "BY",
    name: {
      en: "Belarus",
      es: "Bielorrusia",
      pt: "Bielorrússia",
      fr: "Biélorussie",
    },
  },
  {
    code: "BZ",
    name: { en: "Belize", es: "Belice", pt: "Belize", fr: "Belize" },
  },
  {
    code: "CA",
    name: { en: "Canada", es: "Canadá", pt: "Canadá", fr: "Canada" },
  },
  {
    code: "CC",
    name: {
      en: "Cocos (Keeling) Islands",
      es: "Islas Cocos",
      pt: "Ilhas Cocos (Keeling)",
      fr: "Îles Cocos (Keeling)",
    },
  },
  {
    code: "CD",
    name: {
      en: "Congo, Democratic Republic of the",
      es: "Congo, República Democrática del",
      pt: "Congo, República Democrática do",
      fr: "Congo, République démocratique du",
    },
  },
  {
    code: "CF",
    name: {
      en: "Central African Republic",
      es: "República Centroafricana",
      pt: "República Centro-Africana",
      fr: "République centrafricaine",
    },
  },
  {
    code: "CG",
    name: {
      en: "Congo, Republic of the",
      es: "Congo, República del",
      pt: "Congo, República do",
      fr: "Congo, République du",
    },
  },
  {
    code: "CH",
    name: { en: "Switzerland", es: "Suiza", pt: "Suíça", fr: "Suisse" },
  },
  {
    code: "CI",
    name: {
      en: "Cote d'Ivoire",
      es: "Costa de Marfil",
      pt: "Costa do Marfim",
      fr: "Côte d'Ivoire",
    },
  },
  {
    code: "CK",
    name: {
      en: "Cook Islands",
      es: "Islas Cook",
      pt: "Ilhas Cook",
      fr: "Îles Cook",
    },
  },
  {
    code: "CL",
    name: { en: "Chile", es: "Chile", pt: "Chile", fr: "Chili" },
  },
  {
    code: "CM",
    name: { en: "Cameroon", es: "Camerún", pt: "Camarões", fr: "Cameroun" },
  },
  {
    code: "CN",
    name: { en: "China", es: "China", pt: "China", fr: "Chine" },
  },
  {
    code: "CO",
    name: { en: "Colombia", es: "Colombia", pt: "Colômbia", fr: "Colombie" },
    subdivisions: {
      type: { en: "Department", es: "Departamento" },
      list: [
        "Amazonas",
        "Antioquia",
        "Arauca",
        "Atlántico",
        "Bolívar",
        "Boyacá",
        "Caldas",
        "Caquetá",
        "Casanare",
        "Cauca",
        "Cesar",
        "Chocó",
        "Córdoba",
        "Cundinamarca",
        "Guainía",
        "Guaviare",
        "Huila",
        "La Guajira",
        "Magdalena",
        "Meta",
        "Nariño",
        "Norte de Santander",
        "Putumayo",
        "Quindío",
        "Risaralda",
        "San Andrés y Providencia",
        "Santander",
        "Sucre",
        "Tolima",
        "Valle del Cauca",
        "Vaupés",
        "Vichada",
      ],
    },
  },
  {
    code: "CR",
    name: {
      en: "Costa Rica",
      es: "Costa Rica",
      pt: "Costa Rica",
      fr: "Costa Rica",
    },
  },
  {
    code: "CU",
    name: { en: "Cuba", es: "Cuba", pt: "Cuba", fr: "Cuba" },
  },
  {
    code: "CV",
    name: {
      en: "Cape Verde",
      es: "Cabo Verde",
      pt: "Cabo Verde",
      fr: "Cap-Vert",
    },
  },
  {
    code: "CW",
    name: { en: "Curacao", es: "Curazao", pt: "Curaçau", fr: "Curaçao" },
  },
  {
    code: "CX",
    name: {
      en: "Christmas Island",
      es: "Isla de Navidad",
      pt: "Ilha Christmas",
      fr: "Île Christmas",
    },
  },
  {
    code: "CY",
    name: { en: "Cyprus", es: "Chipre", pt: "Chipre", fr: "Chypre" },
  },
  {
    code: "CZ",
    name: {
      en: "Czech Republic",
      es: "República Checa",
      pt: "República Tcheca",
      fr: "République tchèque",
    },
  },
  {
    code: "DE",
    name: { en: "Germany", es: "Alemania", pt: "Alemanha", fr: "Allemagne" },
  },
  {
    code: "DJ",
    name: { en: "Djibouti", es: "Yibuti", pt: "Djibuti", fr: "Djibouti" },
  },
  {
    code: "DK",
    name: { en: "Denmark", es: "Dinamarca", pt: "Dinamarca", fr: "Danemark" },
  },
  {
    code: "DM",
    name: { en: "Dominica", es: "Dominica", pt: "Dominica", fr: "Dominique" },
  },
  {
    code: "DO",
    name: {
      en: "Dominican Republic",
      es: "República Dominicana",
      pt: "República Dominicana",
      fr: "République dominicaine",
    },
  },
  {
    code: "DZ",
    name: { en: "Algeria", es: "Argelia", pt: "Argélia", fr: "Algérie" },
  },
  {
    code: "EC",
    name: { en: "Ecuador", es: "Ecuador", pt: "Equador", fr: "Équateur" },
  },
  {
    code: "EE",
    name: { en: "Estonia", es: "Estonia", pt: "Estônia", fr: "Estonie" },
  },
  {
    code: "EG",
    name: { en: "Egypt", es: "Egipto", pt: "Egito", fr: "Égypte" },
  },
  {
    code: "EH",
    name: {
      en: "Western Sahara",
      es: "Sahara Occidental",
      pt: "Saara Ocidental",
      fr: "Sahara occidental",
    },
  },
  {
    code: "ER",
    name: { en: "Eritrea", es: "Eritrea", pt: "Eritreia", fr: "Érythrée" },
  },
  {
    code: "ES",
    name: { en: "Spain", es: "España", pt: "Espanha", fr: "Espagne" },
  },
  {
    code: "ET",
    name: { en: "Ethiopia", es: "Etiopía", pt: "Etiópia", fr: "Éthiopie" },
  },
  {
    code: "FI",
    name: { en: "Finland", es: "Finlandia", pt: "Finlândia", fr: "Finlande" },
  },
  {
    code: "FJ",
    name: { en: "Fiji", es: "Fiyi", pt: "Fiji", fr: "Fidji" },
  },
  {
    code: "FK",
    name: {
      en: "Falkland Islands (Islas Malvinas)",
      es: "Islas Malvinas",
      pt: "Ilhas Malvinas",
      fr: "Îles Falkland (Malvinas)",
    },
  },
  {
    code: "FM",
    name: {
      en: "Micronesia",
      es: "Micronesia",
      pt: "Micronésia",
      fr: "Micronésie",
    },
  },
  {
    code: "FO",
    name: {
      en: "Faroe Islands",
      es: "Islas Feroe",
      pt: "Ilhas Faroé",
      fr: "Îles Féroé",
    },
  },
  {
    code: "FR",
    name: { en: "France", es: "Francia", pt: "França", fr: "France" },
  },
  {
    code: "GA",
    name: { en: "Gabon", es: "Gabón", pt: "Gabão", fr: "Gabon" },
  },
  {
    code: "GB",
    name: {
      en: "United Kingdom",
      es: "Reino Unido",
      pt: "Reino Unido",
      fr: "Royaume-Uni",
    },
  },
  {
    code: "GD",
    name: { en: "Grenada", es: "Granada", pt: "Granada", fr: "Grenade" },
  },
  {
    code: "GE",
    name: { en: "Georgia", es: "Georgia", pt: "Geórgia", fr: "Géorgie" },
  },
  {
    code: "GF",
    name: {
      en: "French Guiana",
      es: "Guayana Francesa",
      pt: "Guiana Francesa",
      fr: "Guyane française",
    },
  },
  {
    code: "GG",
    name: { en: "Guernsey", es: "Guernsey", pt: "Guernsey", fr: "Guernesey" },
  },
  {
    code: "GH",
    name: { en: "Ghana", es: "Ghana", pt: "Gana", fr: "Ghana" },
  },
  {
    code: "GI",
    name: {
      en: "Gibraltar",
      es: "Gibraltar",
      pt: "Gibraltar",
      fr: "Gibraltar",
    },
  },
  {
    code: "GL",
    name: {
      en: "Greenland",
      es: "Groenlandia",
      pt: "Groenlândia",
      fr: "Groenland",
    },
  },
  {
    code: "GM",
    name: { en: "Gambia", es: "Gambia", pt: "Gâmbia", fr: "Gambie" },
  },
  {
    code: "GN",
    name: { en: "Guinea", es: "Guinea", pt: "Guiné", fr: "Guinée" },
  },
  {
    code: "GP",
    name: {
      en: "Guadeloupe",
      es: "Guadalupe",
      pt: "Guadalupe",
      fr: "Guadeloupe",
    },
  },
  {
    code: "GQ",
    name: {
      en: "Equatorial Guinea",
      es: "Guinea Ecuatorial",
      pt: "Guiné Equatorial",
      fr: "Guinée équatoriale",
    },
  },
  {
    code: "GR",
    name: { en: "Greece", es: "Grecia", pt: "Grécia", fr: "Grèce" },
  },
  {
    code: "GS",
    name: {
      en: "South Georgia and the South Sandwich Islands",
      es: "Georgia del Sur y las Islas Sandwich del Sur",
      pt: "Geórgia do Sul e Ilhas Sandwich do Sul",
      fr: "Géorgie du Sud et les îles Sandwich du Sud",
    },
  },
  {
    code: "GT",
    name: {
      en: "Guatemala",
      es: "Guatemala",
      pt: "Guatemala",
      fr: "Guatemala",
    },
  },
  {
    code: "GU",
    name: { en: "Guam", es: "Guam", pt: "Guam", fr: "Guam" },
  },
  {
    code: "GW",
    name: {
      en: "Guinea-Bissau",
      es: "Guinea-Bissau",
      pt: "Guiné-Bissau",
      fr: "Guinée-Bissau",
    },
  },
  {
    code: "GY",
    name: { en: "Guyana", es: "Guyana", pt: "Guiana", fr: "Guyana" },
  },
  {
    code: "HK",
    name: {
      en: "Hong Kong",
      es: "Hong Kong",
      pt: "Hong Kong",
      fr: "Hong Kong",
    },
  },
  {
    code: "HM",
    name: {
      en: "Heard Island and McDonald Islands",
      es: "Islas Heard y McDonald",
      pt: "Ilha Heard e Ilhas McDonald",
      fr: "Îles Heard et McDonald",
    },
  },
  {
    code: "HN",
    name: { en: "Honduras", es: "Honduras", pt: "Honduras", fr: "Honduras" },
  },
  {
    code: "HR",
    name: { en: "Croatia", es: "Croacia", pt: "Croácia", fr: "Croatie" },
  },
  {
    code: "HT",
    name: { en: "Haiti", es: "Haití", pt: "Haiti", fr: "Haïti" },
  },
  {
    code: "HU",
    name: { en: "Hungary", es: "Hungría", pt: "Hungria", fr: "Hongrie" },
  },
  {
    code: "ID",
    name: {
      en: "Indonesia",
      es: "Indonesia",
      pt: "Indonésia",
      fr: "Indonésie",
    },
  },
  {
    code: "IE",
    name: { en: "Ireland", es: "Irlanda", pt: "Irlanda", fr: "Irlande" },
  },
  {
    code: "IL",
    name: { en: "Israel", es: "Israel", pt: "Israel", fr: "Israël" },
  },
  {
    code: "IM",
    name: {
      en: "Isle of Man",
      es: "Isla de Man",
      pt: "Ilha de Man",
      fr: "Île de Man",
    },
  },
  {
    code: "IN",
    name: { en: "India", es: "India", pt: "Índia", fr: "Inde" },
  },
  // {
  //   code: "IO",
  //   name: {
  //     en: "British Indian Ocean Territory",
  //     es: "Territorio Británico del Océano Índico",
  //     pt: "Território Britânico do Oceano Índico",
  //     fr: "Territoire britannique de l'océan Indien",
  //   },
  // },
  {
    code: "IQ",
    name: { en: "Iraq", es: "Irak", pt: "Iraque", fr: "Irak" },
  },
  {
    code: "IR",
    name: { en: "Iran", es: "Irán", pt: "Irã", fr: "Iran" },
  },
  {
    code: "IS",
    name: { en: "Iceland", es: "Islandia", pt: "Islândia", fr: "Islande" },
  },
  {
    code: "IT",
    name: { en: "Italy", es: "Italia", pt: "Itália", fr: "Italie" },
  },
  {
    code: "JE",
    name: { en: "Jersey", es: "Jersey", pt: "Jersey", fr: "Jersey" },
  },
  {
    code: "JM",
    name: { en: "Jamaica", es: "Jamaica", pt: "Jamaica", fr: "Jamaïque" },
  },
  {
    code: "JO",
    name: { en: "Jordan", es: "Jordania", pt: "Jordânia", fr: "Jordanie" },
  },
  {
    code: "JP",
    name: { en: "Japan", es: "Japón", pt: "Japão", fr: "Japon" },
  },
  {
    code: "KE",
    name: { en: "Kenya", es: "Kenia", pt: "Quênia", fr: "Kenya" },
  },
  {
    code: "KG",
    name: {
      en: "Kyrgyzstan",
      es: "Kirguistán",
      pt: "Quirguistão",
      fr: "Kirghizistan",
    },
  },
  {
    code: "KH",
    name: { en: "Cambodia", es: "Camboya", pt: "Camboja", fr: "Cambodge" },
  },
  {
    code: "KI",
    name: { en: "Kiribati", es: "Kiribati", pt: "Kiribati", fr: "Kiribati" },
  },
  {
    code: "KM",
    name: { en: "Comoros", es: "Comoras", pt: "Comores", fr: "Comores" },
  },
  {
    code: "KN",
    name: {
      en: "Saint Kitts and Nevis",
      es: "San Cristóbal y Nieves",
      pt: "São Cristóvão e Nevis",
      fr: "Saint-Kitts-et-Nevis",
    },
  },
  {
    code: "KP",
    name: {
      en: "North Korea",
      es: "Corea del Norte",
      pt: "Coreia do Norte",
      fr: "Corée du Nord",
    },
  },
  {
    code: "KR",
    name: {
      en: "South Korea",
      es: "Corea del Sur",
      pt: "Coreia do Sul",
      fr: "Corée du Sud",
    },
  },
  {
    code: "KW",
    name: { en: "Kuwait", es: "Kuwait", pt: "Kuwait", fr: "Koweït" },
  },
  {
    code: "KY",
    name: {
      en: "Cayman Islands",
      es: "Islas Caimán",
      pt: "Ilhas Cayman",
      fr: "Îles Caïmans",
    },
  },
  {
    code: "KZ",
    name: {
      en: "Kazakhstan",
      es: "Kazajistán",
      pt: "Cazaquistão",
      fr: "Kazakhstan",
    },
  },
  {
    code: "LA",
    name: { en: "Laos", es: "Laos", pt: "Laos", fr: "Laos" },
  },
  {
    code: "LB",
    name: { en: "Lebanon", es: "Líbano", pt: "Líbano", fr: "Liban" },
  },
  {
    code: "LC",
    name: {
      en: "Saint Lucia",
      es: "Santa Lucía",
      pt: "Santa Lúcia",
      fr: "Sainte-Lucie",
    },
  },
  {
    code: "LI",
    name: {
      en: "Liechtenstein",
      es: "Liechtenstein",
      pt: "Liechtenstein",
      fr: "Liechtenstein",
    },
  },
  {
    code: "LK",
    name: {
      en: "Sri Lanka",
      es: "Sri Lanka",
      pt: "Sri Lanka",
      fr: "Sri Lanka",
    },
  },
  {
    code: "LR",
    name: { en: "Liberia", es: "Liberia", pt: "Libéria", fr: "Libéria" },
  },
  {
    code: "LS",
    name: { en: "Lesotho", es: "Lesoto", pt: "Lesoto", fr: "Lesotho" },
  },
  {
    code: "LT",
    name: { en: "Lithuania", es: "Lituania", pt: "Lituânia", fr: "Lituanie" },
  },
  {
    code: "LU",
    name: {
      en: "Luxembourg",
      es: "Luxemburgo",
      pt: "Luxemburgo",
      fr: "Luxembourg",
    },
  },
  {
    code: "LV",
    name: { en: "Latvia", es: "Letonia", pt: "Letônia", fr: "Lettonie" },
  },
  {
    code: "LY",
    name: { en: "Libya", es: "Libia", pt: "Líbia", fr: "Libye" },
  },
  {
    code: "MA",
    name: { en: "Morocco", es: "Marruecos", pt: "Marrocos", fr: "Maroc" },
  },
  {
    code: "MC",
    name: { en: "Monaco", es: "Mónaco", pt: "Mônaco", fr: "Monaco" },
  },
  {
    code: "MD",
    name: { en: "Moldova", es: "Moldavia", pt: "Moldávia", fr: "Moldavie" },
  },
  {
    code: "ME",
    name: {
      en: "Montenegro",
      es: "Montenegro",
      pt: "Montenegro",
      fr: "Monténégro",
    },
  },
  {
    code: "MF",
    name: {
      en: "Saint Martin",
      es: "San Martín",
      pt: "São Martinho",
      fr: "Saint-Martin",
    },
  },
  {
    code: "MG",
    name: {
      en: "Madagascar",
      es: "Madagascar",
      pt: "Madagáscar",
      fr: "Madagascar",
    },
  },
  {
    code: "MH",
    name: {
      en: "Marshall Islands",
      es: "Islas Marshall",
      pt: "Ilhas Marshall",
      fr: "Îles Marshall",
    },
  },
  {
    code: "MK",
    name: {
      en: "North Macedonia",
      es: "Macedonia del Norte",
      pt: "Macedônia do Norte",
      fr: "Macédoine du Nord",
    },
  },
  {
    code: "ML",
    name: { en: "Mali", es: "Malí", pt: "Mali", fr: "Mali" },
  },
  {
    code: "MM",
    name: {
      en: "Myanmar",
      es: "Myanmar",
      pt: "Mianmar",
      fr: "Myanmar (Birmanie)",
    },
  },
  {
    code: "MN",
    name: { en: "Mongolia", es: "Mongolia", pt: "Mongólia", fr: "Mongolie" },
  },
  {
    code: "MO",
    name: { en: "Macao", es: "Macao", pt: "Macau", fr: "Macao" },
  },
  {
    code: "MP",
    name: {
      en: "Northern Mariana Islands",
      es: "Islas Marianas del Norte",
      pt: "Ilhas Marianas do Norte",
      fr: "Îles Mariannes du Nord",
    },
  },
  {
    code: "MQ",
    name: {
      en: "Martinique",
      es: "Martinica",
      pt: "Martinica",
      fr: "Martinique",
    },
  },
  {
    code: "MR",
    name: {
      en: "Mauritania",
      es: "Mauritania",
      pt: "Mauritânia",
      fr: "Mauritanie",
    },
  },
  {
    code: "MS",
    name: {
      en: "Montserrat",
      es: "Montserrat",
      pt: "Montserrat",
      fr: "Montserrat",
    },
  },
  {
    code: "MT",
    name: { en: "Malta", es: "Malta", pt: "Malta", fr: "Malte" },
  },
  {
    code: "MU",
    name: { en: "Mauritius", es: "Mauricio", pt: "Maurício", fr: "Maurice" },
  },
  {
    code: "MV",
    name: { en: "Maldives", es: "Maldivas", pt: "Maldivas", fr: "Maldives" },
  },
  {
    code: "MW",
    name: { en: "Malawi", es: "Malaui", pt: "Malaui", fr: "Malawi" },
  },
  {
    code: "MX",
    name: { en: "Mexico", es: "México", pt: "México", fr: "Mexique" },
  },
  {
    code: "MY",
    name: { en: "Malaysia", es: "Malasia", pt: "Malásia", fr: "Malaisie" },
  },
  {
    code: "MZ",
    name: {
      en: "Mozambique",
      es: "Mozambique",
      pt: "Moçambique",
      fr: "Mozambique",
    },
  },
  {
    code: "NA",
    name: { en: "Namibia", es: "Namibia", pt: "Namíbia", fr: "Namibie" },
  },
  {
    code: "NC",
    name: {
      en: "New Caledonia",
      es: "Nueva Caledonia",
      pt: "Nova Caledônia",
      fr: "Nouvelle-Calédonie",
    },
  },
  {
    code: "NE",
    name: { en: "Niger", es: "Níger", pt: "Níger", fr: "Niger" },
  },
  {
    code: "NF",
    name: {
      en: "Norfolk Island",
      es: "Isla Norfolk",
      pt: "Ilha Norfolk",
      fr: "Île Norfolk",
    },
  },
  {
    code: "NG",
    name: { en: "Nigeria", es: "Nigeria", pt: "Nigéria", fr: "Nigéria" },
  },
  {
    code: "NI",
    name: {
      en: "Nicaragua",
      es: "Nicaragua",
      pt: "Nicarágua",
      fr: "Nicaragua",
    },
  },
  {
    code: "NL",
    name: {
      en: "Netherlands",
      es: "Países Bajos",
      pt: "Países Baixos",
      fr: "Pays-Bas",
    },
  },
  {
    code: "NO",
    name: { en: "Norway", es: "Noruega", pt: "Noruega", fr: "Norvège" },
  },
  {
    code: "NP",
    name: { en: "Nepal", es: "Nepal", pt: "Nepal", fr: "Népal" },
  },
  {
    code: "NR",
    name: { en: "Nauru", es: "Nauru", pt: "Nauru", fr: "Nauru" },
  },
  {
    code: "NU",
    name: { en: "Niue", es: "Niue", pt: "Niue", fr: "Niue" },
  },
  {
    code: "NZ",
    name: {
      en: "New Zealand",
      es: "Nueva Zelanda",
      pt: "Nova Zelândia",
      fr: "Nouvelle-Zélande",
    },
  },
  {
    code: "OM",
    name: { en: "Oman", es: "Omán", pt: "Omã", fr: "Oman" },
  },
  {
    code: "PA",
    name: { en: "Panama", es: "Panamá", pt: "Panamá", fr: "Panama" },
  },
  {
    code: "PE",
    name: { en: "Peru", es: "Perú", pt: "Peru", fr: "Pérou" },
  },
  {
    code: "PF",
    name: {
      en: "French Polynesia",
      es: "Polinesia Francesa",
      pt: "Polinésia Francesa",
      fr: "Polynésie française",
    },
  },
  {
    code: "PG",
    name: {
      en: "Papua New Guinea",
      es: "Papúa Nueva Guinea",
      pt: "Papua-Nova Guiné",
      fr: "Papouasie-Nouvelle-Guinée",
    },
  },
  {
    code: "PH",
    name: {
      en: "Philippines",
      es: "Filipinas",
      pt: "Filipinas",
      fr: "Philippines",
    },
  },
  {
    code: "PK",
    name: { en: "Pakistan", es: "Pakistán", pt: "Paquistão", fr: "Pakistan" },
  },
  {
    code: "PL",
    name: { en: "Poland", es: "Polonia", pt: "Polônia", fr: "Pologne" },
  },
  {
    code: "PM",
    name: {
      en: "Saint Pierre and Miquelon",
      es: "San Pedro y Miquelón",
      pt: "Saint Pierre e Miquelon",
      fr: "Saint-Pierre-et-Miquelon",
    },
  },
  {
    code: "PN",
    name: {
      en: "Pitcairn Islands",
      es: "Islas Pitcairn",
      pt: "Ilhas Pitcairn",
      fr: "Îles Pitcairn",
    },
  },
  {
    code: "PR",
    name: {
      en: "Puerto Rico",
      es: "Puerto Rico",
      pt: "Porto Rico",
      fr: "Porto Rico",
    },
  },
  {
    code: "PS",
    name: {
      en: "Palestine",
      es: "Palestina",
      pt: "Palestina",
      fr: "Palestine",
    },
  },
  {
    code: "PT",
    name: { en: "Portugal", es: "Portugal", pt: "Portugal", fr: "Portugal" },
  },
  {
    code: "PW",
    name: { en: "Palau", es: "Palaos", pt: "Palau", fr: "Palaos" },
  },
  {
    code: "PY",
    name: { en: "Paraguay", es: "Paraguay", pt: "Paraguai", fr: "Paraguay" },
  },
  {
    code: "QA",
    name: { en: "Qatar", es: "Catar", pt: "Catar", fr: "Qatar" },
  },
  {
    code: "RE",
    name: { en: "Réunion", es: "Reunión", pt: "Reunião", fr: "Réunion" },
  },
  {
    code: "RO",
    name: { en: "Romania", es: "Rumanía", pt: "Romênia", fr: "Roumanie" },
  },
  {
    code: "RS",
    name: { en: "Serbia", es: "Serbia", pt: "Sérvia", fr: "Serbie" },
  },
  {
    code: "RU",
    name: { en: "Russia", es: "Rusia", pt: "Rússia", fr: "Russie" },
  },
  {
    code: "RW",
    name: { en: "Rwanda", es: "Ruanda", pt: "Ruanda", fr: "Rwanda" },
  },
  {
    code: "SA",
    name: {
      en: "Saudi Arabia",
      es: "Arabia Saudita",
      pt: "Arábia Saudita",
      fr: "Arabie saoudite",
    },
  },
  {
    code: "SB",
    name: {
      en: "Solomon Islands",
      es: "Islas Salomón",
      pt: "Ilhas Salomão",
      fr: "Îles Salomon",
    },
  },
  {
    code: "SC",
    name: {
      en: "Seychelles",
      es: "Seychelles",
      pt: "Seicheles",
      fr: "Seychelles",
    },
  },
  {
    code: "SD",
    name: { en: "Sudan", es: "Sudán", pt: "Sudão", fr: "Soudan" },
  },
  {
    code: "SE",
    name: { en: "Sweden", es: "Suecia", pt: "Suécia", fr: "Suède" },
  },
  {
    code: "SG",
    name: { en: "Singapore", es: "Singapur", pt: "Singapura", fr: "Singapour" },
  },
  {
    code: "SH",
    name: {
      en: "Saint Helena",
      es: "Santa Elena",
      pt: "Santa Helena",
      fr: "Sainte-Hélène",
    },
  },
  {
    code: "SI",
    name: { en: "Slovenia", es: "Eslovenia", pt: "Eslovênia", fr: "Slovénie" },
  },
  {
    code: "SJ",
    name: {
      en: "Svalbard and Jan Mayen",
      es: "Svalbard y Jan Mayen",
      pt: "Svalbard e Jan Mayen",
      fr: "Svalbard et Jan Mayen",
    },
  },
  {
    code: "SK",
    name: {
      en: "Slovakia",
      es: "Eslovaquia",
      pt: "Eslováquia",
      fr: "Slovaquie",
    },
  },
  {
    code: "SL",
    name: {
      en: "Sierra Leone",
      es: "Sierra Leona",
      pt: "Serra Leoa",
      fr: "Sierra Leone",
    },
  },
  {
    code: "SM",
    name: {
      en: "San Marino",
      es: "San Marino",
      pt: "San Marino",
      fr: "Saint-Marin",
    },
  },
  {
    code: "SN",
    name: { en: "Senegal", es: "Senegal", pt: "Senegal", fr: "Sénégal" },
  },
  {
    code: "SO",
    name: { en: "Somalia", es: "Somalia", pt: "Somália", fr: "Somalie" },
  },
  {
    code: "SR",
    name: { en: "Suriname", es: "Surinam", pt: "Suriname", fr: "Suriname" },
  },
  {
    code: "SS",
    name: {
      en: "South Sudan",
      es: "Sudán del Sur",
      pt: "Sudão do Sul",
      fr: "Soudan du Sud",
    },
  },
  {
    code: "ST",
    name: {
      en: "São Tomé and Príncipe",
      es: "Santo Tomé y Príncipe",
      pt: "São Tomé e Príncipe",
      fr: "Sao Tomé-et-Principe",
    },
  },
  {
    code: "SV",
    name: {
      en: "El Salvador",
      es: "El Salvador",
      pt: "El Salvador",
      fr: "Salvador",
    },
  },
  {
    code: "SX",
    name: {
      en: "Sint Maarten",
      es: "Sint Maarten",
      pt: "Sint Maarten",
      fr: "Sint Maarten",
    },
  },
  {
    code: "SY",
    name: { en: "Syria", es: "Siria", pt: "Síria", fr: "Syrie" },
  },
  {
    code: "SZ",
    name: { en: "Eswatini", es: "Esuatini", pt: "Essuatíni", fr: "Eswatini" },
  },
  {
    code: "TC",
    name: {
      en: "Turks and Caicos Islands",
      es: "Islas Turcas y Caicos",
      pt: "Ilhas Turks e Caicos",
      fr: "Îles Turques-et-Caïques",
    },
  },
  {
    code: "TD",
    name: { en: "Chad", es: "Chad", pt: "Chade", fr: "Tchad" },
  },
  {
    code: "TF",
    name: {
      en: "French Southern and Antarctic Lands",
      es: "Tierras Australes y Antárticas Francesas",
      pt: "Terra Austral e Antártica Francesa",
      fr: "Terres australes et antarctiques françaises",
    },
  },
  {
    code: "TG",
    name: { en: "Togo", es: "Togo", pt: "Togo", fr: "Togo" },
  },
  {
    code: "TH",
    name: { en: "Thailand", es: "Tailandia", pt: "Tailândia", fr: "Thaïlande" },
  },
  {
    code: "TJ",
    name: {
      en: "Tajikistan",
      es: "Tayikistán",
      pt: "Tajiquistão",
      fr: "Tadjikistan",
    },
  },
  {
    code: "TK",
    name: { en: "Tokelau", es: "Tokelau", pt: "Tokelau", fr: "Tokelau" },
  },
  {
    code: "TL",
    name: {
      en: "East Timor",
      es: "Timor Oriental",
      pt: "Timor-Leste",
      fr: "Timor oriental",
    },
  },
  {
    code: "TM",
    name: {
      en: "Turkmenistan",
      es: "Turkmenistán",
      pt: "Turcomenistão",
      fr: "Turkménistan",
    },
  },
  {
    code: "TN",
    name: { en: "Tunisia", es: "Túnez", pt: "Tunísia", fr: "Tunisie" },
  },
  {
    code: "TO",
    name: { en: "Tonga", es: "Tonga", pt: "Tonga", fr: "Tonga" },
  },
  {
    code: "TR",
    name: { en: "Turkey", es: "Turquía", pt: "Turquia", fr: "Turquie" },
  },
  {
    code: "TT",
    name: {
      en: "Trinidad and Tobago",
      es: "Trinidad y Tobago",
      pt: "Trinidad e Tobago",
      fr: "Trinité-et-Tobago",
    },
  },
  {
    code: "TV",
    name: { en: "Tuvalu", es: "Tuvalu", pt: "Tuvalu", fr: "Tuvalu" },
  },
  {
    code: "TW",
    name: { en: "Taiwan", es: "Taiwán", pt: "Taiwan", fr: "Taïwan" },
  },
  {
    code: "TZ",
    name: { en: "Tanzania", es: "Tanzania", pt: "Tanzânia", fr: "Tanzanie" },
  },
  {
    code: "UA",
    name: { en: "Ukraine", es: "Ucrania", pt: "Ucrânia", fr: "Ukraine" },
  },
  {
    code: "UG",
    name: { en: "Uganda", es: "Uganda", pt: "Uganda", fr: "Ouganda" },
  },
  // {
  //   code: "UM",
  //   name: {
  //     en: "United States Minor Outlying Islands",
  //     es: "Islas Ultramarinas Menores de Estados Unidos",
  //     pt: "Ilhas Menores Distantes dos Estados Unidos",
  //     fr: "Îles mineures éloignées des États-Unis",
  //   },
  // },
  {
    code: "US",
    name: {
      en: "United States",
      es: "Estados Unidos",
      pt: "Estados Unidos",
      fr: "États-Unis",
    },
  },
  {
    code: "UY",
    name: { en: "Uruguay", es: "Uruguay", pt: "Uruguai", fr: "Uruguay" },
  },
  {
    code: "UZ",
    name: {
      en: "Uzbekistan",
      es: "Uzbekistán",
      pt: "Usbequistão",
      fr: "Ouzbékistan",
    },
  },
  {
    code: "VA",
    name: {
      en: "Vatican City",
      es: "Ciudad del Vaticano",
      pt: "Cidade do Vaticano",
      fr: "Cité du Vatican",
    },
  },
  {
    code: "VC",
    name: {
      en: "Saint Vincent and the Grenadines",
      es: "San Vicente y las Granadinas",
      pt: "São Vicente e Granadinas",
      fr: "Saint-Vincent-et-les Grenadines",
    },
  },
  {
    code: "VE",
    name: {
      en: "Venezuela",
      es: "Venezuela",
      pt: "Venezuela",
      fr: "Venezuela",
    },
  },
  {
    code: "VG",
    name: {
      en: "British Virgin Islands",
      es: "Islas Vírgenes Británicas",
      pt: "Ilhas Virgens Britânicas",
      fr: "Îles Vierges britanniques",
    },
  },
  {
    code: "VI",
    name: {
      en: "United States Virgin Islands",
      es: "Islas Vírgenes de los Estados Unidos",
      pt: "Ilhas Virgens Americanas",
      fr: "Îles Vierges américaines",
    },
  },
  {
    code: "VN",
    name: { en: "Vietnam", es: "Vietnam", pt: "Vietnã", fr: "Vietnam" },
  },
  {
    code: "VU",
    name: { en: "Vanuatu", es: "Vanuatu", pt: "Vanuatu", fr: "Vanuatu" },
  },
  {
    code: "WF",
    name: {
      en: "Wallis and Futuna",
      es: "Wallis y Futuna",
      pt: "Wallis e Futuna",
      fr: "Wallis-et-Futuna",
    },
  },
  {
    code: "WS",
    name: { en: "Samoa", es: "Samoa", pt: "Samoa", fr: "Samoa" },
  },
  {
    code: "YE",
    name: { en: "Yemen", es: "Yemen", pt: "Iêmen", fr: "Yémen" },
  },
  {
    code: "YT",
    name: { en: "Mayotte", es: "Mayotte", pt: "Mayotte", fr: "Mayotte" },
  },
  {
    code: "ZA",
    name: {
      en: "South Africa",
      es: "Sudáfrica",
      pt: "África do Sul",
      fr: "Afrique du Sud",
    },
  },
  {
    code: "ZM",
    name: { en: "Zambia", es: "Zambia", pt: "Zâmbia", fr: "Zambie" },
  },
  {
    code: "ZW",
    name: { en: "Zimbabwe", es: "Zimbabue", pt: "Zimbábue", fr: "Zimbabwe" },
  },
];

const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "fr", name: "Français" },
  { code: "es", name: "Español" },
  { code: "pt", name: "Português" },
];

const CURRENCIES: Currencies = {
  AD: { code: "EUR", name: "Euro" },
  AE: { code: "AED", name: "United Arab Emirates Dirham" },
  AF: { code: "AFN", name: "Afghan Afghani" },
  AG: { code: "XCD", name: "East Caribbean Dollar" },
  AI: { code: "XCD", name: "East Caribbean Dollar" },
  AL: { code: "ALL", name: "Albanian Lek" },
  AM: { code: "AMD", name: "Armenian Dram" },
  AN: { code: "ANG", name: "Netherlands Antillean Guilder" },
  AO: { code: "AOA", name: "Angolan Kwanza" },
  // AQ: { code: "None", name: "No Matching Currency" },
  AR: { code: "ARS", name: "Argentine Peso" },
  // AS: { code: "None", name: "No Matching Currency" },
  AT: { code: "EUR", name: "Euro" },
  AU: { code: "AUD", name: "Australian Dollar" },
  AW: { code: "AWG", name: "Aruban Florin" },
  // AX: { code: "None", name: "No Matching Currency" },
  AZ: { code: "AZN", name: "Azerbaijani Manat" },
  BA: { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
  BB: { code: "BBD", name: "Barbadian Dollar" },
  BD: { code: "BDT", name: "Bangladeshi Taka" },
  BE: { code: "EUR", name: "Euro" },
  BF: { code: "XOF", name: "CFA Franc BCEAO" },
  BG: { code: "BGN", name: "Bulgarian Lev" },
  BH: { code: "BHD", name: "Bahraini Dinar" },
  BI: { code: "BIF", name: "Burundian Franc" },
  BJ: { code: "XOF", name: "CFA Franc BCEAO" },
  // BL: { code: "None", name: "No Matching Currency" },
  BM: { code: "BMD", name: "Bermudan Dollar" },
  BN: { code: "BND", name: "Brunei Dollar" },
  BO: { code: "BOB", name: "Bolivian Boliviano" },
  // BQ: { code: "None", name: "No Matching Currency" },
  BR: { code: "BRL", name: "Brazilian Real" },
  BS: { code: "BSD", name: "Bahamian Dollar" },
  BT: { code: "BTN", name: "Bhutanese Ngultrum" },
  // BV: { code: "None", name: "No Matching Currency" },
  BW: { code: "BWP", name: "Botswanan Pula" },
  BY: { code: "BYN", name: "New Belarusian Ruble" },
  BZ: { code: "BZD", name: "Belize Dollar" },
  CA: { code: "CAD", name: "Canadian Dollar" },
  // CC: { code: "None", name: "No Matching Currency" },
  CD: { code: "CDF", name: "Congolese Franc" },
  CF: { code: "XAF", name: "CFA Franc BEAC" },
  // CG: { code: "None", name: "No Matching Currency" },
  CH: { code: "CHF", name: "Swiss Franc" },
  CI: { code: "XOF", name: "CFA Franc BCEAO" },
  CK: { code: "NZD", name: "New Zealand Dollar" },
  CL: { code: "CLP", name: "Chilean Peso" },
  CM: { code: "XAF", name: "CFA Franc BEAC" },
  CN: { code: "CNY", name: "Chinese Yuan" },
  CO: { code: "COP", name: "Colombian Peso" },
  CR: { code: "CRC", name: "Costa Rican Colón" },
  CU: { code: "CUP", name: "Cuban Peso" },
  CV: { code: "CVE", name: "Cape Verdean Escudo" },
  // CW: { code: "None", name: "No Matching Currency" },
  CX: { code: "AUD", name: "Australian Dollar" },
  CY: { code: "EUR", name: "Euro" },
  CZ: { code: "CZK", name: "Czech Republic Koruna" },
  DE: { code: "EUR", name: "Euro" },
  DJ: { code: "DJF", name: "Djiboutian Franc" },
  DK: { code: "DKK", name: "Danish Krone" },
  DM: { code: "XCD", name: "East Caribbean Dollar" },
  DO: { code: "DOP", name: "Dominican Peso" },
  DZ: { code: "DZD", name: "Algerian Dinar" },
  EC: { code: "USD", name: "United States Dollar" },
  EE: { code: "EUR", name: "Euro" },
  EG: { code: "EGP", name: "Egyptian Pound" },
  // EH: { code: "None", name: "No Matching Currency" },
  ER: { code: "ERN", name: "Eritrean Nakfa" },
  ES: { code: "EUR", name: "Euro" },
  ET: { code: "ETB", name: "Ethiopian Birr" },
  EU: { code: "EUR", name: "Euro" },
  FI: { code: "EUR", name: "Euro" },
  FJ: { code: "FJD", name: "Fijian Dollar" },
  FK: { code: "FKP", name: "Falkland Islands Pound" },
  FM: { code: "USD", name: "United States Dollar" },
  FO: { code: "DKK", name: "Danish Krone" },
  GA: { code: "XAF", name: "CFA Franc BEAC" },
  GB: { code: "GBP", name: "British Pound Sterling" },
  GD: { code: "XCD", name: "East Caribbean Dollar" },
  GE: { code: "GEL", name: "Georgian Lari" },
  GF: { code: "EUR", name: "Euro" },
  GG: { code: "GGP", name: "Guernsey Pound" },
  GH: { code: "GHS", name: "Ghanaian Cedi" },
  GI: { code: "GIP", name: "Gibraltar Pound" },
  GL: { code: "DKK", name: "Danish Krone" },
  GM: { code: "GMD", name: "Gambian Dalasi" },
  GN: { code: "GNF", name: "Guinean Franc" },
  GP: { code: "EUR", name: "Euro" },
  GQ: { code: "XAF", name: "CFA Franc BEAC" },
  GR: { code: "EUR", name: "Euro" },
  // GS: { code: null, name: "South Georgia and the South Sandwich Islands" },
  GT: { code: "GTQ", name: "Guatemalan Quetzal" },
  GU: { code: "USD", name: "United States Dollar" },
  GW: { code: "XOF", name: "CFA Franc BCEAO" },
  GY: { code: "GYD", name: "Guyanaese Dollar" },
  HK: { code: "HKD", name: "Hong Kong Dollar" },
  // HM: { code: null, name: "Heard and McDonald Islands" },
  HN: { code: "HNL", name: "Honduran Lempira" },
  HR: { code: "HRK", name: "Croatian Kuna" },
  HT: { code: "HTG", name: "Haitian Gourde" },
  HU: { code: "HUF", name: "Hungarian Forint" },
  IC: { code: "EUR", name: "Euro" },
  ID: { code: "IDR", name: "Indonesian Rupiah" },
  IE: { code: "EUR", name: "Euro" },
  IL: { code: "ILS", name: "Israeli New Shekel" },
  IM: { code: "GBP", name: "British Pound Sterling" },
  IN: { code: "INR", name: "Indian Rupee" },
  IO: { code: "USD", name: "United States Dollar" },
  IQ: { code: "IQD", name: "Iraqi Dinar" },
  IR: { code: "IRR", name: "Iranian Rial" },
  IS: { code: "ISK", name: "Icelandic Króna" },
  IT: { code: "EUR", name: "Euro" },
  JE: { code: "GBP", name: "British Pound Sterling" },
  JM: { code: "JMD", name: "Jamaican Dollar" },
  JO: { code: "JOD", name: "Jordanian Dinar" },
  JP: { code: "JPY", name: "Japanese Yen" },
  KE: { code: "KES", name: "Kenyan Shilling" },
  KG: { code: "KGS", name: "Kyrgyzstani Som" },
  KH: { code: "KHR", name: "Cambodian Riel" },
  KI: { code: "AUD", name: "Australian Dollar" },
  KM: { code: "KMF", name: "Comorian Franc" },
  KN: { code: "XCD", name: "East Caribbean Dollar" },
  KP: { code: "KPW", name: "North Korean Won" },
  KR: { code: "KRW", name: "South Korean Won" },
  KW: { code: "KWD", name: "Kuwaiti Dinar" },
  KY: { code: "KYD", name: "Cayman Islands Dollar" },
  KZ: { code: "KZT", name: "Kazakhstani Tenge" },
  LA: { code: "LAK", name: "Laotian Kip" },
  LB: { code: "LBP", name: "Lebanese Pound" },
  LC: { code: "XCD", name: "East Caribbean Dollar" },
  LI: { code: "CHF", name: "Swiss Franc" },
  LK: { code: "LKR", name: "Sri Lankan Rupee" },
  LR: { code: "LRD", name: "Liberian Dollar" },
  LS: { code: "LSL", name: "Lesotho Loti" },
  LT: { code: "EUR", name: "Euro" },
  LU: { code: "EUR", name: "Euro" },
  LV: { code: "EUR", name: "Euro" },
  LY: { code: "LYD", name: "Libyan Dinar" },
  MA: { code: "MAD", name: "Moroccan Dirham" },
  MC: { code: "EUR", name: "Euro" },
  MD: { code: "MDL", name: "Moldovan Leu" },
  ME: { code: "EUR", name: "Euro" },
  MF: { code: "EUR", name: "Euro" },
  MG: { code: "MGA", name: "Malagasy Ariary" },
  MH: { code: "USD", name: "United States Dollar" },
  MK: { code: "MKD", name: "Macedonian Denar" },
  ML: { code: "XOF", name: "CFA Franc BCEAO" },
  MM: { code: "MMK", name: "Myanmar Kyat" },
  MN: { code: "MNT", name: "Mongolian Tugrik" },
  MO: { code: "MOP", name: "Macanese Pataca" },
  MP: { code: "USD", name: "United States Dollar" },
  MQ: { code: "EUR", name: "Euro" },
  MR: { code: "MRU", name: "Mauritanian Ouguiya" },
  MS: { code: "XCD", name: "East Caribbean Dollar" },
  MT: { code: "EUR", name: "Euro" },
  MU: { code: "MUR", name: "Mauritian Rupee" },
  MV: { code: "MVR", name: "Maldivian Rufiyaa" },
  MW: { code: "MWK", name: "Malawian Kwacha" },
  MX: { code: "MXN", name: "Mexican Peso" },
  MY: { code: "MYR", name: "Malaysian Ringgit" },
  MZ: { code: "MZN", name: "Mozambican Metical" },
  NA: { code: "NAD", name: "Namibian Dollar" },
  NC: { code: "XPF", name: "CFP Franc" },
  NE: { code: "XOF", name: "CFA Franc BCEAO" },
  NF: { code: "AUD", name: "Australian Dollar" },
  NG: { code: "NGN", name: "Nigerian Naira" },
  NI: { code: "NIO", name: "Nicaraguan Córdoba" },
  NL: { code: "EUR", name: "Euro" },
  NO: { code: "NOK", name: "Norwegian Krone" },
  NP: { code: "NPR", name: "Nepalese Rupee" },
  NR: { code: "AUD", name: "Australian Dollar" },
  NU: { code: "NZD", name: "New Zealand Dollar" },
  NZ: { code: "NZD", name: "New Zealand Dollar" },
  OM: { code: "OMR", name: "Omani Rial" },
  PA: { code: "PAB", name: "Panamanian Balboa" },
  PE: { code: "PEN", name: "Peruvian Nuevo Sol" },
  PF: { code: "XPF", name: "CFP Franc" },
  PG: { code: "PGK", name: "Papua New Guinean Kina" },
  PH: { code: "PHP", name: "Philippine Peso" },
  PK: { code: "PKR", name: "Pakistani Rupee" },
  PL: { code: "PLN", name: "Polish Złoty" },
  PM: { code: "EUR", name: "Euro" },
  PN: { code: "NZD", name: "New Zealand Dollar" },
  PR: { code: "USD", name: "United States Dollar" },
  PS: { code: "ILS", name: "Israeli New Shekel" },
  PT: { code: "EUR", name: "Euro" },
  PW: { code: "USD", name: "United States Dollar" },
  PY: { code: "PYG", name: "Paraguayan Guarani" },
  QA: { code: "QAR", name: "Qatari Rial" },
  RE: { code: "EUR", name: "Euro" },
  RO: { code: "RON", name: "Romanian Leu" },
  RS: { code: "RSD", name: "Serbian Dinar" },
  RU: { code: "RUB", name: "Russian Ruble" },
  RW: { code: "RWF", name: "Rwandan Franc" },
  SA: { code: "SAR", name: "Saudi Riyal" },
  SB: { code: "SBD", name: "Solomon Islands Dollar" },
  SC: { code: "SCR", name: "Seychellois Rupee" },
  SD: { code: "SDG", name: "Sudanese Pound" },
  SE: { code: "SEK", name: "Swedish Krona" },
  SG: { code: "SGD", name: "Singapore Dollar" },
  SH: { code: "SHP", name: "Saint Helena Pound" },
  SI: { code: "EUR", name: "Euro" },
  SJ: { code: "NOK", name: "Norwegian Krone" },
  SK: { code: "EUR", name: "Euro" },
  SL: { code: "SLL", name: "Sierra Leonean Leone" },
  SM: { code: "EUR", name: "Euro" },
  SN: { code: "XOF", name: "CFA Franc BCEAO" },
  SO: { code: "SOS", name: "Somali Shilling" },
  SR: { code: "SRD", name: "Surinamese Dollar" },
  SS: { code: "SSP", name: "South Sudanese Pound" },
  ST: { code: "STN", name: "São Tomé and Príncipe Dobra" },
  SV: { code: "USD", name: "United States Dollar" },
  SX: { code: "ANG", name: "Netherlands Antillean Guilder" },
  SY: { code: "SYP", name: "Syrian Pound" },
  SZ: { code: "SZL", name: "Swazi Lilangeni" },
  TC: { code: "USD", name: "United States Dollar" },
  TD: { code: "XAF", name: "CFA Franc BEAC" },
  TF: { code: "EUR", name: "Euro" },
  TG: { code: "XOF", name: "CFA Franc BCEAO" },
  TH: { code: "THB", name: "Thai Baht" },
  TJ: { code: "TJS", name: "Tajikistani Somoni" },
  TK: { code: "NZD", name: "New Zealand Dollar" },
  TL: { code: "USD", name: "United States Dollar" },
  TM: { code: "TMT", name: "Turkmenistani Manat" },
  TN: { code: "TND", name: "Tunisian Dinar" },
  TO: { code: "TOP", name: "Tongan Pa'anga" },
  TR: { code: "TRY", name: "Turkish Lira" },
  TT: { code: "TTD", name: "Trinidad and Tobago Dollar" },
  TV: { code: "AUD", name: "Australian Dollar" },
  TW: { code: "TWD", name: "New Taiwan Dollar" },
  TZ: { code: "TZS", name: "Tanzanian Shilling" },
  UA: { code: "UAH", name: "Ukrainian Hryvnia" },
  UG: { code: "UGX", name: "Ugandan Shilling" },
  UM: { code: "USD", name: "United States Dollar" },
  US: { code: "USD", name: "United States Dollar" },
  UY: { code: "UYU", name: "Uruguayan Peso" },
  UZ: { code: "UZS", name: "Uzbekistan Som" },
  VA: { code: "EUR", name: "Euro" },
  VC: { code: "XCD", name: "East Caribbean Dollar" },
  VE: { code: "VES", name: "Venezuelan Bolívar" },
  VG: { code: "USD", name: "United States Dollar" },
  VI: { code: "USD", name: "United States Dollar" },
  VN: { code: "VND", name: "Vietnamese Đồng" },
  VU: { code: "VUV", name: "Vanuatu Vatu" },
  WF: { code: "XPF", name: "CFP Franc" },
  WS: { code: "WST", name: "Samoan Tala" },
  YE: { code: "YER", name: "Yemeni Rial" },
  YT: { code: "EUR", name: "Euro" },
  ZA: { code: "ZAR", name: "South African Rand" },
  ZM: { code: "ZMW", name: "Zambian Kwacha" },
  ZW: { code: "ZWL", name: "Zimbabwean Dollar" },
};

const PHONE_PREFIXES: PhonePrefixes = {
  AF: "93",
  AL: "355",
  DZ: "213",
  AS: "1-684",
  AD: "376",
  AO: "244",
  AI: "1-264",
  AQ: "672",
  AG: "1-268",
  AR: "54",
  AM: "374",
  AW: "297",
  AU: "61",
  AT: "43",
  AZ: "994",
  BS: "1-242",
  BH: "973",
  BD: "880",
  BB: "1-246",
  BY: "375",
  BE: "32",
  BZ: "501",
  BJ: "229",
  BM: "1-441",
  BT: "975",
  BO: "591",
  BA: "387",
  BW: "267",
  BR: "55",
  IO: "246",
  VG: "1-284",
  BN: "673",
  BG: "359",
  BF: "226",
  BI: "257",
  KH: "855",
  CM: "237",
  CA: "1",
  CV: "238",
  KY: "1-345",
  CF: "236",
  TD: "235",
  CL: "56",
  CN: "86",
  CX: "61",
  CC: "61",
  CO: "57",
  KM: "269",
  CK: "682",
  CR: "506",
  HR: "385",
  CU: "53",
  CW: "599",
  CY: "357",
  CZ: "420",
  CD: "243",
  DK: "45",
  DJ: "253",
  DM: "1-767",
  DO: "1-809, 1-829, 1-849",
  TL: "670",
  EC: "593",
  EG: "20",
  SV: "503",
  GQ: "240",
  ER: "291",
  EE: "372",
  ET: "251",
  FK: "500",
  FO: "298",
  FJ: "679",
  FI: "358",
  FR: "33",
  PF: "689",
  GA: "241",
  GM: "220",
  GE: "995",
  DE: "49",
  GH: "233",
  GI: "350",
  GR: "30",
  GL: "299",
  GD: "1-473",
  GU: "1-671",
  GT: "502",
  GG: "44-1481",
  GN: "224",
  GW: "245",
  GY: "592",
  HT: "509",
  HN: "504",
  HK: "852",
  HU: "36",
  IS: "354",
  IN: "91",
  ID: "62",
  IR: "98",
  IQ: "964",
  IE: "353",
  IM: "44-1624",
  IL: "972",
  IT: "39",
  CI: "225",
  JM: "1-876",
  JP: "81",
  JE: "44-1534",
  JO: "962",
  KZ: "7",
  KE: "254",
  KI: "686",
  XK: "383",
  KW: "965",
  KG: "996",
  LA: "856",
  LV: "371",
  LB: "961",
  LS: "266",
  LR: "231",
  LY: "218",
  LI: "423",
  LT: "370",
  LU: "352",
  MO: "853",
  MK: "389",
  MG: "261",
  MW: "265",
  MY: "60",
  MV: "960",
  ML: "223",
  MT: "356",
  MH: "692",
  MR: "222",
  MU: "230",
  YT: "262",
  MX: "52",
  FM: "691",
  MD: "373",
  MC: "377",
  MN: "976",
  ME: "382",
  MS: "1-664",
  MA: "212",
  MZ: "258",
  MM: "95",
  NA: "264",
  NR: "674",
  NP: "977",
  NL: "31",
  AN: "599",
  NC: "687",
  NZ: "64",
  NI: "505",
  NE: "227",
  NG: "234",
  NU: "683",
  KP: "850",
  MP: "1-670",
  NO: "47",
  OM: "968",
  PK: "92",
  PW: "680",
  PS: "970",
  PA: "507",
  PG: "675",
  PY: "595",
  PE: "51",
  PH: "63",
  PN: "64",
  PL: "48",
  PT: "351",
  PR: "1-787, 1-939",
  QA: "974",
  CG: "242",
  RE: "262",
  RO: "40",
  RU: "7",
  RW: "250",
  BL: "590",
  SH: "290",
  KN: "1-869",
  LC: "1-758",
  MF: "590",
  PM: "508",
  VC: "1-784",
  WS: "685",
  SM: "378",
  ST: "239",
  SA: "966",
  SN: "221",
  RS: "381",
  SC: "248",
  SL: "232",
  SG: "65",
  SX: "1-721",
  SK: "421",
  SI: "386",
  SB: "677",
  SO: "252",
  ZA: "27",
  KR: "82",
  SS: "211",
  ES: "34",
  LK: "94",
  SD: "249",
  SR: "597",
  SJ: "47",
  SZ: "268",
  SE: "46",
  CH: "41",
  SY: "963",
  TW: "886",
  TJ: "992",
  TZ: "255",
  TH: "66",
  TG: "228",
  TK: "690",
  TO: "676",
  TT: "1-868",
  TN: "216",
  TR: "90",
  TM: "993",
  TC: "1-649",
  TV: "688",
  VI: "1-340",
  UG: "256",
  UA: "380",
  AE: "971",
  GB: "44",
  US: "1",
  UY: "598",
  UZ: "998",
  VU: "678",
  VA: "379",
  VE: "58",
  VN: "84",
  WF: "681",
  EH: "212",
  YE: "967",
  ZM: "260",
  ZW: "263",
};

const THIRD_PARTY_CHARGES = {
  card: 0.03,
  bankAccount: 0.015,
};

const CARD_BRAND_IMG = {
  visa,
  mastercard,
};

export {
  CONTENT_STYLES,
  USER_COUNTRIES,
  TRANSFER_COUNTRIES,
  LANGUAGES,
  CURRENCIES,
  PHONE_PREFIXES,
  THIRD_PARTY_CHARGES,
  CARD_BRAND_IMG,
};
