import visa from "./assets/visa.svg";
import mastercard from "./assets/mastercard.svg";

const SITE_PADDING_X = "200px";

const USER_COUNTRIES = [
  { code: "AT", name: { en: "Austria", es: "Austria" } },
  { code: "AU", name: { en: "Australia", es: "Australia" } },
  { code: "BE", name: { en: "Belgium", es: "Bélgica" } },
  { code: "CA", name: { en: "Canada", es: "Canadá" } },
  { code: "ES", name: { en: "Spain", es: "España" } },
  { code: "CH", name: { en: "Switzerland", es: "Suiza" } },
  { code: "DE", name: { en: "Germany", es: "Alemania" } },
  { code: "DK", name: { en: "Denmark", es: "Dinamarca" } },
  { code: "FR", name: { en: "France", es: "Francia" } },
  { code: "GB", name: { en: "United Kingdom", es: "Reino Unido" } },
  { code: "US", name: { en: "United States", es: "Estados Unidos" } },
];

// const TRANSFER_COUNTRIES = [
//   { code: "AD", name: "Andorra" },
//   { code: "AE", name: "United Arab Emirates" },
//   { code: "AF", name: "Afghanistan" },
//   { code: "AG", name: "Antigua and Barbuda" },
//   { code: "AI", name: "Anguilla" },
//   { code: "AL", name: "Albania" },
//   { code: "AM", name: "Armenia" },
//   { code: "AN", name: "Netherlands Antilles" },
//   { code: "AO", name: "Angola" },
//   { code: "AQ", name: "Antarctica" },
//   { code: "AR", name: "Argentina" },
//   { code: "AS", name: "American Samoa" },
//   { code: "AT", name: "Austria" },
//   { code: "AU", name: "Australia" },
//   { code: "AW", name: "Aruba" },
//   { code: "AX", name: "Åland Islands" },
//   { code: "AZ", name: "Azerbaijan" },
//   { code: "BA", name: "Bosnia and Herzegovina" },
//   { code: "BB", name: "Barbados" },
//   { code: "BD", name: "Bangladesh" },
//   { code: "BE", name: "Belgium" },
//   { code: "BF", name: "Burkina Faso" },
//   { code: "BG", name: "Bulgaria" },
//   { code: "BH", name: "Bahrain" },
//   { code: "BI", name: "Burundi" },
//   { code: "BJ", name: "Benin" },
//   //   { code: "BL", name: "Saint Barthélemy" },
//   { code: "BM", name: "Bermuda" },
//   { code: "BN", name: "Brunei Darussalam" },
//   { code: "BO", name: "Bolivia" },
//   //   { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
//   { code: "BR", name: "Brazil" },
//   { code: "BS", name: "Bahamas" },
//   { code: "BT", name: "Bhutan" },
//   //   { code: "BV", name: "Bouvet Island" },
//   { code: "BW", name: "Botswana" },
//   { code: "BY", name: "Belarus" },
//   { code: "BZ", name: "Belize" },
//   { code: "CA", name: "Canada" },
//   { code: "CC", name: "Cocos (Keeling) Islands" },
//   { code: "CD", name: "Democratic Republic of Congo" },
//   { code: "CF", name: "Central African Republic" },
//   { code: "CG", name: "Congo" },
//   { code: "CH", name: "Switzerland" },
//   { code: "CI", name: "Côte D'Ivoire" },
//   { code: "CK", name: "Cook Islands" },
//   { code: "CL", name: "Chile" },
//   { code: "CM", name: "Cameroon" },
//   { code: "CN", name: "China" },
//   { code: "CO", name: "Colombia" },
//   { code: "CR", name: "Costa Rica" },
//   { code: "CU", name: "Cuba" },
//   { code: "CV", name: "Cape Verde" },
//   { code: "CW", name: "Curaçao" },
//   { code: "CX", name: "Christmas Island" },
//   { code: "CY", name: "Cyprus" },
//   { code: "CZ", name: "Czech Republic" },
//   { code: "DE", name: "Germany" },
//   { code: "DJ", name: "Djibouti" },
//   { code: "DK", name: "Denmark" },
//   { code: "DM", name: "Dominica" },
//   { code: "DO", name: "Dominican Republic" },
//   { code: "DZ", name: "Algeria" },
//   { code: "EC", name: "Ecuador" },
//   { code: "EE", name: "Estonia" },
//   { code: "EG", name: "Egypt" },
//   { code: "EH", name: "Western Sahara" },
//   { code: "ER", name: "Eritrea" },
//   { code: "ES", name: "Spain" },
//   { code: "ET", name: "Ethiopia" },
//   //   { code: "EU", name: "European Union" },
//   { code: "FI", name: "Finland" },
//   { code: "FJ", name: "Fiji" },
//   { code: "FK", name: "Falkland Islands (Malvinas)" },
//   { code: "FM", name: "Micronesia, Federated States Of" },
//   { code: "FO", name: "Faroe Islands" },
//   { code: "FR", name: "France" },
//   { code: "GA", name: "Gabon" },
//   { code: "GB", name: "United Kingdom" },
//   { code: "GD", name: "Grenada" },
//   { code: "GE", name: "Georgia" },
//   //   { code: "GF", name: "French Guiana" },
//   { code: "GG", name: "Guernsey" },
//   { code: "GH", name: "Ghana" },
//   { code: "GI", name: "Gibraltar" },
//   { code: "GL", name: "Greenland" },
//   { code: "GM", name: "Gambia" },
//   { code: "GN", name: "Guinea" },
//   { code: "GP", name: "Guadeloupe" },
//   { code: "GQ", name: "Equatorial Guinea" },
//   { code: "GR", name: "Greece" },
//   //   { code: "GS", name: "South Georgia and the South Sandwich Islands" },
//   { code: "GT", name: "Guatemala" },
//   { code: "GU", name: "Guam" },
//   { code: "GW", name: "Guinea-Bissau" },
//   { code: "GY", name: "Guyana" },
//   { code: "HK", name: "Hong Kong" },
//   //   { code: "HM", name: "Heard and McDonald Islands" },
//   { code: "HN", name: "Honduras" },
//   { code: "HR", name: "Croatia" },
//   { code: "US", name: "United States" },
// ];

const TRANSFER_COUNTRIES = [
  {
    code: "AD",
    name: { en: "Andorra", es: "Andorra" },
    subdivisions: { type: "N/A" },
  },
  {
    code: "AE",
    name: { en: "United Arab Emirates", es: "Emiratos Árabes Unidos" },
    subdivisions: { type: "Emirates" },
  },
  {
    code: "AF",
    name: { en: "Afghanistan", es: "Afganistán" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "AG",
    name: { en: "Antigua and Barbuda", es: "Antigua y Barbuda" },
    subdivisions: { type: "Parishes" },
  },
  {
    code: "AI",
    name: { en: "Anguilla", es: "Anguila" },
    subdivisions: { type: "Parishes" },
  },
  {
    code: "AL",
    name: { en: "Albania", es: "Albania" },
    subdivisions: { type: "Counties" },
  },
  {
    code: "AM",
    name: { en: "Armenia", es: "Armenia" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "AN",
    name: { en: "Netherlands Antilles", es: "Antillas Neerlandesas" },
    subdivisions: { type: "N/A" },
  },
  {
    code: "AO",
    name: { en: "Angola", es: "Angola" },
    subdivisions: { type: "Provinces" },
  },
  // { code: "AQ", name: "Antarctica" },
  {
    code: "AR",
    name: { en: "Argentina", es: "Argentina" },
    subdivisions: { type: "Provinces" },
  },
  // { code: "AS", name: "American Samoa" },
  {
    code: "AT",
    name: { en: "Austria", es: "Austria" },
    subdivisions: { type: "States" },
  },
  {
    code: "AU",
    name: { en: "Australia", es: "Australia" },
    subdivisions: { type: "States and Territories" },
  },
  {
    code: "AW",
    name: { en: "Aruba", es: "Aruba" },
    subdivisions: { type: "N/A" },
  },
  // { code: "AX", name: "Åland Islands" },
  {
    code: "AZ",
    name: { en: "Azerbaijan", es: "Azerbaiyán" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "BA",
    name: { en: "Bosnia and Herzegovina", es: "Bosnia y Herzegovina" },
    subdivisions: { type: "Entities" },
  },
  {
    code: "BB",
    name: { en: "Barbados", es: "Barbados" },
    subdivisions: { type: "Parishes" },
  },
  {
    code: "BD",
    name: { en: "Bangladesh", es: "Bangladés" },
    subdivisions: { type: "Divisions" },
  },
  {
    code: "BE",
    name: { en: "Belgium", es: "Bélgica" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "BF",
    name: { en: "Burkina Faso", es: "Burkina Faso" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "BG",
    name: { en: "Bulgaria", es: "Bulgaria" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "BH",
    name: { en: "Bahrain", es: "Baréin" },
    subdivisions: { type: "Governorates" },
  },
  {
    code: "BI",
    name: { en: "Burundi", es: "Burundi" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "BJ",
    name: { en: "Benin", es: "Benín" },
    subdivisions: { type: "Departments" },
  },
  // { code: "BL", name: "Saint Barthélemy" },
  {
    code: "BM",
    name: { en: "Bermuda", es: "Bermudas" },
    subdivisions: { type: "Parishes" },
  },
  {
    code: "BN",
    name: { en: "Brunei Darussalam", es: "Brunéi" },
    subdivisions: { type: "Districts" },
  },
  {
    code: "BO",
    name: { en: "Bolivia", es: "Bolivia" },
    subdivisions: { type: "Departments" },
  },
  // { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  {
    code: "BR",
    name: { en: "Brazil", es: "Brasil" },
    subdivisions: { type: "States" },
  },
  {
    code: "BS",
    name: { en: "Bahamas", es: "Bahamas" },
    subdivisions: { type: "Islands" },
  },
  {
    code: "BT",
    name: { en: "Bhutan", es: "Bután" },
    subdivisions: { type: "Districts" },
  },
  // { code: "BV", name: "Bouvet Island" },
  {
    code: "BW",
    name: { en: "Botswana", es: "Botsuana" },
    subdivisions: { type: "Districts" },
  },
  {
    code: "BY",
    name: { en: "Belarus", es: "Bielorrusia" },
    subdivisions: { type: "Oblasts" },
  },
  {
    code: "BZ",
    name: { en: "Belize", es: "Belice" },
    subdivisions: { type: "Districts" },
  },
  {
    code: "CA",
    name: { en: "Canada", es: "Canadá" },
    subdivisions: { type: "Provinces and Territories" },
  },
  // { code: "CC", name: "Cocos (Keeling) Islands" },
  {
    code: "CD",
    name: {
      en: "Congo, The Democratic Republic Of The",
      es: "República Democrática del Congo",
    },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "CF",
    name: { en: "Central African Republic", es: "República Centroafricana" },
    subdivisions: { type: "Prefectures" },
  },
  // { code: "CG", name: "Congo" },
  {
    code: "CH",
    name: { en: "Switzerland", es: "Suiza" },
    subdivisions: { type: "Cantons" },
  },
  {
    code: "CI",
    name: { en: "Côte D'Ivoire", es: "Costa de Marfil" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "CK",
    name: { en: "Cook Islands", es: "Islas Cook" },
    subdivisions: { type: "Islands" },
  },
  {
    code: "CL",
    name: { en: "Chile", es: "Chile" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "CM",
    name: { en: "Cameroon", es: "Camerún" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "CN",
    name: { en: "China", es: "China" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "CO",
    name: { en: "Colombia", es: "Colombia" },
    subdivisions: { type: "Departments" },
  },
  {
    code: "CR",
    name: { en: "Costa Rica", es: "Costa Rica" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "CU",
    name: { en: "Cuba", es: "Cuba" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "CV",
    name: { en: "Cape Verde", es: "Cabo Verde" },
    subdivisions: { type: "Municipalities" },
  },
  // { code: "CW", name: "Curaçao" },
  {
    code: "CX",
    name: { en: "Christmas Island", es: "Isla de Navidad" },
    subdivisions: { type: "Shire" },
  },
  {
    code: "CY",
    name: { en: "Cyprus", es: "Chipre" },
    subdivisions: { type: "Districts" },
  },
  {
    code: "CZ",
    name: { en: "Czech Republic", es: "República Checa" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "DE",
    name: { en: "Germany", es: "Alemania" },
    subdivisions: { type: "States" },
  },
  {
    code: "DJ",
    name: { en: "Djibouti", es: "Yibuti" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "DK",
    name: { en: "Denmark", es: "Dinamarca" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "DM",
    name: { en: "Dominica", es: "Dominica" },
    subdivisions: { type: "Parishes" },
  },
  {
    code: "DO",
    name: { en: "Dominican Republic", es: "República Dominicana" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "DZ",
    name: { en: "Algeria", es: "Argelia" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "EC",
    name: { en: "Ecuador", es: "Ecuador" },
    subdivisions: { type: "Provinces" },
  },
  {
    code: "EE",
    name: { en: "Estonia", es: "Estonia" },
    subdivisions: { type: "Counties" },
  },
  {
    code: "EG",
    name: { en: "Egypt", es: "Egipto" },
    subdivisions: { type: "Governorates" },
  },
  // { code: "EH", name: "Western Sahara" },
  {
    code: "ER",
    name: { en: "Eritrea", es: "Eritrea" },
    subdivisions: { type: "Regions" },
  },
  {
    code: "ES",
    name: { en: "Spain", es: "España" },
    subdivisions: { type: "Comunidades Autónomas" },
  },
  {
    code: "ET",
    name: { en: "Ethiopia", es: "Etiopía" },
    subdivisions: { type: "Regions" },
  },
  // { code: "EU", name: "European Union" },
  { code: "FI", name: { en: "Finland", es: "Finlandia" } },
  { code: "FJ", name: { en: "Fiji", es: "Fiyi" } },
  {
    code: "FK",
    name: { en: "Falkland Islands (Malvinas)", es: "Islas Malvinas" },
  },
  {
    code: "FM",
    name: {
      en: "Micronesia, Federated States Of",
      es: "Micronesia, Estados Federados de",
    },
  },
  { code: "FO", name: { en: "Faroe Islands", es: "Islas Feroe" } },
  { code: "FR", name: { en: "France", es: "Francia" } },
  { code: "GA", name: { en: "Gabon", es: "Gabón" } },
  { code: "GB", name: { en: "United Kingdom", es: "Reino Unido" } },
  { code: "GD", name: { en: "Grenada", es: "Granada" } },
  { code: "GE", name: { en: "Georgia", es: "Georgia" } },
  // { code: "GF", name: "French Guiana" },
  { code: "GG", name: { en: "Guernsey", es: "Guernsey" } },
  { code: "GH", name: { en: "Ghana", es: "Ghana" } },
  { code: "GI", name: { en: "Gibraltar", es: "Gibraltar" } },
  { code: "GL", name: { en: "Greenland", es: "Groenlandia" } },
  { code: "GM", name: { en: "Gambia", es: "Gambia" } },
  { code: "GN", name: { en: "Guinea", es: "Guinea" } },
  { code: "GP", name: { en: "Guadeloupe", es: "Guadalupe" } },
  { code: "GQ", name: { en: "Equatorial Guinea", es: "Guinea Ecuatorial" } },
  { code: "GR", name: { en: "Greece", es: "Grecia" } },
  // { code: "GS", name: "South Georgia and the South Sandwich Islands" },
  { code: "GT", name: { en: "Guatemala", es: "Guatemala" } },
  { code: "GU", name: { en: "Guam", es: "Guam" } },
  { code: "GW", name: { en: "Guinea-Bissau", es: "Guinea-Bisáu" } },
  { code: "GY", name: { en: "Guyana", es: "Guyana" } },
  { code: "HK", name: { en: "Hong Kong", es: "Hong Kong" } },
  // { code: "HM", name: "Heard and McDonald Islands" },
  { code: "HN", name: { en: "Honduras", es: "Honduras" } },
  { code: "HR", name: { en: "Croatia", es: "Croacia" } },
  { code: "HT", name: { en: "Haiti", es: "Haití" } },
  { code: "HU", name: { en: "Hungary", es: "Hungría" } },
  { code: "IC", name: { en: "Canary Islands", es: "Islas Canarias" } },
  { code: "ID", name: { en: "Indonesia", es: "Indonesia" } },
  { code: "IE", name: { en: "Ireland", es: "Irlanda" } },
  { code: "IL", name: { en: "Israel", es: "Israel" } },
  { code: "IM", name: { en: "Isle of Man", es: "Isla de Man" } },
  { code: "IN", name: { en: "India", es: "India" } },
  {
    code: "IO",
    name: {
      en: "British Indian Ocean Territory",
      es: "Territorio Británico del Océano Índico",
    },
  },
  { code: "IQ", name: { en: "Iraq", es: "Irak" } },
  {
    code: "IR",
    name: {
      en: "Iran, Islamic Republic Of",
      es: "Irán, República Islámica de",
    },
  },
  { code: "IS", name: { en: "Iceland", es: "Islandia" } },
  { code: "IT", name: { en: "Italy", es: "Italia" } },
  { code: "JE", name: { en: "Jersey", es: "Jersey" } },
  { code: "JM", name: { en: "Jamaica", es: "Jamaica" } },
  { code: "JO", name: { en: "Jordan", es: "Jordania" } },
  { code: "JP", name: { en: "Japan", es: "Japón" } },
  { code: "KE", name: { en: "Kenya", es: "Kenia" } },
  { code: "KG", name: { en: "Kyrgyzstan", es: "Kirguistán" } },
  { code: "KH", name: { en: "Cambodia", es: "Camboya" } },
  { code: "KI", name: { en: "Kiribati", es: "Kiribati" } },
  { code: "KM", name: { en: "Comoros", es: "Comoras" } },
  {
    code: "KN",
    name: { en: "Saint Kitts And Nevis", es: "San Cristóbal y Nieves" },
  },
  {
    code: "KP",
    name: {
      en: "Korea, Democratic People's Republic Of",
      es: "Corea del Norte",
    },
  },
  { code: "KR", name: { en: "Korea, Republic of", es: "Corea del Sur" } },
  { code: "KW", name: { en: "Kuwait", es: "Kuwait" } },
  { code: "KY", name: { en: "Cayman Islands", es: "Islas Caimán" } },
  { code: "KZ", name: { en: "Kazakhstan", es: "Kazajistán" } },
  { code: "LA", name: { en: "Lao People's Democratic Republic", es: "Laos" } },
  { code: "LB", name: { en: "Lebanon", es: "Líbano" } },
  { code: "LC", name: { en: "Saint Lucia", es: "Santa Lucía" } },
  { code: "LI", name: { en: "Liechtenstein", es: "Liechtenstein" } },
  { code: "LK", name: { en: "Sri Lanka", es: "Sri Lanka" } },
  { code: "LR", name: { en: "Liberia", es: "Liberia" } },
  { code: "LS", name: { en: "Lesotho", es: "Lesoto" } },
  { code: "LT", name: { en: "Lithuania", es: "Lituania" } },
  { code: "LU", name: { en: "Luxembourg", es: "Luxemburgo" } },
  { code: "LV", name: { en: "Latvia", es: "Letonia" } },
  { code: "LY", name: { en: "Libya", es: "Libia" } },
  { code: "MA", name: { en: "Morocco", es: "Marruecos" } },
  { code: "MC", name: { en: "Monaco", es: "Mónaco" } },
  { code: "MD", name: { en: "Moldova, Republic of", es: "Moldavia" } },
  { code: "ME", name: { en: "Montenegro", es: "Montenegro" } },
  { code: "MF", name: { en: "Saint Martin", es: "San Martín" } },
  { code: "MG", name: { en: "Madagascar", es: "Madagascar" } },
  { code: "MH", name: { en: "Marshall Islands", es: "Islas Marshall" } },
  {
    code: "MK",
    name: {
      en: "Macedonia, the Former Yugoslav Republic Of",
      es: "Macedonia, Antigua República Yugoslava de",
    },
  },
  { code: "ML", name: { en: "Mali", es: "Malí" } },
  { code: "MM", name: { en: "Myanmar", es: "Myanmar" } },
  { code: "MN", name: { en: "Mongolia", es: "Mongolia" } },
  { code: "MO", name: { en: "Macao", es: "Macao" } },
  {
    code: "MP",
    name: { en: "Northern Mariana Islands", es: "Islas Marianas del Norte" },
  },
  { code: "MQ", name: { en: "Martinique", es: "Martinica" } },
  { code: "MR", name: { en: "Mauritania", es: "Mauritania" } },
  { code: "MS", name: { en: "Montserrat", es: "Montserrat" } },
  { code: "MT", name: { en: "Malta", es: "Malta" } },
  { code: "MU", name: { en: "Mauritius", es: "Mauricio" } },
  { code: "MV", name: { en: "Maldives", es: "Maldivas" } },
  { code: "MW", name: { en: "Malawi", es: "Malaui" } },
  { code: "MX", name: { en: "Mexico", es: "México" } },
  { code: "MY", name: { en: "Malaysia", es: "Malasia" } },
  { code: "MZ", name: { en: "Mozambique", es: "Mozambique" } },
  { code: "NA", name: { en: "Namibia", es: "Namibia" } },
  { code: "NC", name: { en: "New Caledonia", es: "Nueva Caledonia" } },
  { code: "NE", name: { en: "Niger", es: "Níger" } },
  { code: "NF", name: { en: "Norfolk Island", es: "Isla Norfolk" } },
  { code: "NG", name: { en: "Nigeria", es: "Nigeria" } },
  { code: "NI", name: { en: "Nicaragua", es: "Nicaragua" } },
  { code: "NL", name: { en: "Netherlands", es: "Países Bajos" } },
  { code: "NO", name: { en: "Norway", es: "Noruega" } },
  { code: "NP", name: { en: "Nepal", es: "Nepal" } },
  { code: "NR", name: { en: "Nauru", es: "Nauru" } },
  { code: "NU", name: { en: "Niue", es: "Niue" } },
  { code: "NZ", name: { en: "New Zealand", es: "Nueva Zelanda" } },
  { code: "OM", name: { en: "Oman", es: "Omán" } },
  { code: "PA", name: { en: "Panama", es: "Panamá" } },
  { code: "PE", name: { en: "Peru", es: "Perú" } },
  { code: "PF", name: { en: "French Polynesia", es: "Polinesia Francesa" } },
  { code: "PG", name: { en: "Papua New Guinea", es: "Papúa Nueva Guinea" } },
  { code: "PH", name: { en: "Philippines", es: "Filipinas" } },
  { code: "PK", name: { en: "Pakistan", es: "Pakistán" } },
  { code: "PL", name: { en: "Poland", es: "Polonia" } },
  {
    code: "PM",
    name: { en: "Saint Pierre And Miquelon", es: "San Pedro y Miquelón" },
  },
  { code: "PN", name: { en: "Pitcairn", es: "Pitcairn" } },
  { code: "PR", name: { en: "Puerto Rico", es: "Puerto Rico" } },
  {
    code: "PS",
    name: { en: "Palestine, State of", es: "Palestina, Estado de" },
  },
  { code: "PT", name: { en: "Portugal", es: "Portugal" } },
  { code: "PW", name: { en: "Palau", es: "Palaos" } },
  { code: "PY", name: { en: "Paraguay", es: "Paraguay" } },
  { code: "QA", name: { en: "Qatar", es: "Catar" } },
  { code: "RE", name: { en: "Réunion", es: "Reunión" } },
  { code: "RO", name: { en: "Romania", es: "Rumanía" } },
  { code: "RS", name: { en: "Serbia", es: "Serbia" } },
  { code: "RU", name: { en: "Russian Federation", es: "Federación Rusa" } },
  { code: "RW", name: { en: "Rwanda", es: "Ruanda" } },
  { code: "SA", name: { en: "Saudi Arabia", es: "Arabia Saudita" } },
  { code: "SB", name: { en: "Solomon Islands", es: "Islas Salomón" } },
  { code: "SC", name: { en: "Seychelles", es: "Seychelles" } },
  { code: "SD", name: { en: "Sudan", es: "Sudán" } },
  { code: "SE", name: { en: "Sweden", es: "Suecia" } },
  { code: "SG", name: { en: "Singapore", es: "Singapur" } },
  { code: "SH", name: { en: "Saint Helena", es: "Santa Elena" } },
  { code: "SI", name: { en: "Slovenia", es: "Eslovenia" } },
  {
    code: "SJ",
    name: { en: "Svalbard And Jan Mayen", es: "Svalbard y Jan Mayen" },
  },
  { code: "SK", name: { en: "Slovakia", es: "Eslovaquia" } },
  { code: "SL", name: { en: "Sierra Leone", es: "Sierra Leona" } },
  { code: "SM", name: { en: "San Marino", es: "San Marino" } },
  { code: "SN", name: { en: "Senegal", es: "Senegal" } },
  { code: "SO", name: { en: "Somalia", es: "Somalia" } },
  { code: "SR", name: { en: "Suriname", es: "Surinam" } },
  { code: "SS", name: { en: "South Sudan", es: "Sudán del Sur" } },
  {
    code: "ST",
    name: { en: "Sao Tome and Principe", es: "Santo Tomé y Príncipe" },
  },
  { code: "SV", name: { en: "El Salvador", es: "El Salvador" } },
  {
    code: "SX",
    name: {
      en: "Sint Maarten (Dutch part)",
      es: "Sint Maarten (parte neerlandesa)",
    },
  },
  {
    code: "SY",
    name: { en: "Syrian Arab Republic", es: "República Árabe Siria" },
  },
  { code: "SZ", name: { en: "Eswatini", es: "Esuatini" } },
  {
    code: "TC",
    name: { en: "Turks and Caicos Islands", es: "Islas Turcas y Caicos" },
  },
  { code: "TD", name: { en: "Chad", es: "Chad" } },
  {
    code: "TF",
    name: {
      en: "French Southern Territories",
      es: "Territorios Australes Franceses",
    },
  },
  { code: "TG", name: { en: "Togo", es: "Togo" } },
  { code: "TH", name: { en: "Thailand", es: "Tailandia" } },
  { code: "TJ", name: { en: "Tajikistan", es: "Tayikistán" } },
  { code: "TK", name: { en: "Tokelau", es: "Tokelau" } },
  { code: "TL", name: { en: "Timor-Leste", es: "Timor Oriental" } },
  { code: "TM", name: { en: "Turkmenistan", es: "Turkmenistán" } },
  { code: "TN", name: { en: "Tunisia", es: "Túnez" } },
  { code: "TO", name: { en: "Tonga", es: "Tonga" } },
  { code: "TR", name: { en: "Turkey", es: "Turquía" } },
  { code: "TT", name: { en: "Trinidad and Tobago", es: "Trinidad y Tobago" } },
  { code: "TV", name: { en: "Tuvalu", es: "Tuvalu" } },
  {
    code: "TW",
    name: { en: "Taiwan, Province Of China", es: "Taiwán, Provincia de China" },
  },
  {
    code: "TZ",
    name: {
      en: "Tanzania, United Republic of",
      es: "Tanzania, República Unida de",
    },
  },
  { code: "UA", name: { en: "Ukraine", es: "Ucrania" } },
  { code: "UG", name: { en: "Uganda", es: "Uganda" } },
  {
    code: "UM",
    name: {
      en: "United States Minor Outlying Islands",
      es: "Islas menores alejadas de los Estados Unidos",
    },
  },
  { code: "US", name: { en: "United States", es: "Estados Unidos" } },
  { code: "UY", name: { en: "Uruguay", es: "Uruguay" } },
  { code: "UZ", name: { en: "Uzbekistan", es: "Uzbekistán" } },
  {
    code: "VA",
    name: {
      en: "Holy See (Vatican City State)",
      es: "Santa Sede (Ciudad del Vaticano)",
    },
  },
  {
    code: "VC",
    name: {
      en: "Saint Vincent And The Grenadines",
      es: "San Vicente y las Granadinas",
    },
  },
  {
    code: "VE",
    name: {
      en: "Venezuela, Bolivarian Republic of",
      es: "Venezuela, República Bolivariana de",
    },
  },
  {
    code: "VG",
    name: { en: "Virgin Islands, British", es: "Islas Vírgenes Británicas" },
  },
  {
    code: "VI",
    name: {
      en: "Virgin Islands, U.S.",
      es: "Islas Vírgenes de los Estados Unidos",
    },
  },
  { code: "VN", name: { en: "Vietnam", es: "Vietnam" } },
  { code: "VU", name: { en: "Vanuatu", es: "Vanuatu" } },
  { code: "WF", name: { en: "Wallis and Futuna", es: "Wallis y Futuna" } },
  { code: "WS", name: { en: "Samoa", es: "Samoa" } },
  { code: "YE", name: { en: "Yemen", es: "Yemen" } },
  { code: "YT", name: { en: "Mayotte", es: "Mayotte" } },
  { code: "ZA", name: { en: "South Africa", es: "Sudáfrica" } },
  { code: "ZM", name: { en: "Zambia", es: "Zambia" } },
  { code: "ZW", name: { en: "Zimbabwe", es: "Zimbabue" } },
];

const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "fr", name: "Français" },
  { code: "es", name: "Español" },
  { code: "pt", name: "Português" },
];

const CURRENCIES = {
  AD: { code: "EUR", name: "Euro" },
  AE: { code: "AED", name: "United Arab Emirates Dirham" },
  AF: { code: "AFN", name: "Afghan Afghani" },
  AG: { code: "XCD", name: "East Caribbean Dollar" },
  AI: { code: "XCD", name: "East Caribbean Dollar" },
  AL: { code: "ALL", name: "Albanian Lek" },
  AM: { code: "AMD", name: "Armenian Dram" },
  AN: { code: "ANG", name: "Netherlands Antillean Guilder" },
  AO: { code: "AOA", name: "Angolan Kwanza" },
  // AQ: { code: "None", name: "No Matching Currency" },
  AR: { code: "ARS", name: "Argentine Peso" },
  // AS: { code: "None", name: "No Matching Currency" },
  AT: { code: "EUR", name: "Euro" },
  AU: { code: "AUD", name: "Australian Dollar" },
  AW: { code: "AWG", name: "Aruban Florin" },
  // AX: { code: "None", name: "No Matching Currency" },
  AZ: { code: "AZN", name: "Azerbaijani Manat" },
  BA: { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
  BB: { code: "BBD", name: "Barbadian Dollar" },
  BD: { code: "BDT", name: "Bangladeshi Taka" },
  BE: { code: "EUR", name: "Euro" },
  BF: { code: "XOF", name: "CFA Franc BCEAO" },
  BG: { code: "BGN", name: "Bulgarian Lev" },
  BH: { code: "BHD", name: "Bahraini Dinar" },
  BI: { code: "BIF", name: "Burundian Franc" },
  BJ: { code: "XOF", name: "CFA Franc BCEAO" },
  // BL: { code: "None", name: "No Matching Currency" },
  BM: { code: "BMD", name: "Bermudan Dollar" },
  BN: { code: "BND", name: "Brunei Dollar" },
  BO: { code: "BOB", name: "Bolivian Boliviano" },
  // BQ: { code: "None", name: "No Matching Currency" },
  BR: { code: "BRL", name: "Brazilian Real" },
  BS: { code: "BSD", name: "Bahamian Dollar" },
  BT: { code: "BTN", name: "Bhutanese Ngultrum" },
  // BV: { code: "None", name: "No Matching Currency" },
  BW: { code: "BWP", name: "Botswanan Pula" },
  BY: { code: "BYN", name: "New Belarusian Ruble" },
  BZ: { code: "BZD", name: "Belize Dollar" },
  CA: { code: "CAD", name: "Canadian Dollar" },
  // CC: { code: "None", name: "No Matching Currency" },
  CD: { code: "CDF", name: "Congolese Franc" },
  CF: { code: "XAF", name: "CFA Franc BEAC" },
  // CG: { code: "None", name: "No Matching Currency" },
  CH: { code: "CHF", name: "Swiss Franc" },
  CI: { code: "XOF", name: "CFA Franc BCEAO" },
  CK: { code: "NZD", name: "New Zealand Dollar" },
  CL: { code: "CLP", name: "Chilean Peso" },
  CM: { code: "XAF", name: "CFA Franc BEAC" },
  CN: { code: "CNY", name: "Chinese Yuan" },
  CO: { code: "COP", name: "Colombian Peso" },
  CR: { code: "CRC", name: "Costa Rican Colón" },
  CU: { code: "CUP", name: "Cuban Peso" },
  CV: { code: "CVE", name: "Cape Verdean Escudo" },
  // CW: { code: "None", name: "No Matching Currency" },
  CX: { code: "AUD", name: "Australian Dollar" },
  CY: { code: "EUR", name: "Euro" },
  CZ: { code: "CZK", name: "Czech Republic Koruna" },
  DE: { code: "EUR", name: "Euro" },
  DJ: { code: "DJF", name: "Djiboutian Franc" },
  DK: { code: "DKK", name: "Danish Krone" },
  DM: { code: "XCD", name: "East Caribbean Dollar" },
  DO: { code: "DOP", name: "Dominican Peso" },
  DZ: { code: "DZD", name: "Algerian Dinar" },
  EC: { code: "USD", name: "United States Dollar" },
  EE: { code: "EUR", name: "Euro" },
  EG: { code: "EGP", name: "Egyptian Pound" },
  // EH: { code: "None", name: "No Matching Currency" },
  ER: { code: "ERN", name: "Eritrean Nakfa" },
  ES: { code: "EUR", name: "Euro" },
  ET: { code: "ETB", name: "Ethiopian Birr" },
  EU: { code: "EUR", name: "Euro" },
  FI: { code: "EUR", name: "Euro" },
  FJ: { code: "FJD", name: "Fijian Dollar" },
  FK: { code: "FKP", name: "Falkland Islands Pound" },
  FM: { code: "USD", name: "United States Dollar" },
  FO: { code: "DKK", name: "Danish Krone" },
  GA: { code: "XAF", name: "CFA Franc BEAC" },
  GB: { code: "GBP", name: "British Pound Sterling" },
  GD: { code: "XCD", name: "East Caribbean Dollar" },
  GE: { code: "GEL", name: "Georgian Lari" },
  GF: { code: "EUR", name: "Euro" },
  GG: { code: "GGP", name: "Guernsey Pound" },
  GH: { code: "GHS", name: "Ghanaian Cedi" },
  GI: { code: "GIP", name: "Gibraltar Pound" },
  GL: { code: "DKK", name: "Danish Krone" },
  GM: { code: "GMD", name: "Gambian Dalasi" },
  GN: { code: "GNF", name: "Guinean Franc" },
  GP: { code: "EUR", name: "Euro" },
  GQ: { code: "XAF", name: "CFA Franc BEAC" },
  GR: { code: "EUR", name: "Euro" },
  // GS: { code: null, name: "South Georgia and the South Sandwich Islands" },
  GT: { code: "GTQ", name: "Guatemalan Quetzal" },
  GU: { code: "USD", name: "United States Dollar" },
  GW: { code: "XOF", name: "CFA Franc BCEAO" },
  GY: { code: "GYD", name: "Guyanaese Dollar" },
  HK: { code: "HKD", name: "Hong Kong Dollar" },
  // HM: { code: null, name: "Heard and McDonald Islands" },
  HN: { code: "HNL", name: "Honduran Lempira" },
  HR: { code: "HRK", name: "Croatian Kuna" },
  HT: { code: "HTG", name: "Haitian Gourde" },
  HU: { code: "HUF", name: "Hungarian Forint" },
  IC: { code: "EUR", name: "Euro" },
  ID: { code: "IDR", name: "Indonesian Rupiah" },
  IE: { code: "EUR", name: "Euro" },
  IL: { code: "ILS", name: "Israeli New Shekel" },
  IM: { code: "GBP", name: "British Pound Sterling" },
  IN: { code: "INR", name: "Indian Rupee" },
  IO: { code: "USD", name: "United States Dollar" },
  IQ: { code: "IQD", name: "Iraqi Dinar" },
  IR: { code: "IRR", name: "Iranian Rial" },
  IS: { code: "ISK", name: "Icelandic Króna" },
  IT: { code: "EUR", name: "Euro" },
  JE: { code: "GBP", name: "British Pound Sterling" },
  JM: { code: "JMD", name: "Jamaican Dollar" },
  JO: { code: "JOD", name: "Jordanian Dinar" },
  JP: { code: "JPY", name: "Japanese Yen" },
  KE: { code: "KES", name: "Kenyan Shilling" },
  KG: { code: "KGS", name: "Kyrgyzstani Som" },
  KH: { code: "KHR", name: "Cambodian Riel" },
  KI: { code: "AUD", name: "Australian Dollar" },
  KM: { code: "KMF", name: "Comorian Franc" },
  KN: { code: "XCD", name: "East Caribbean Dollar" },
  KP: { code: "KPW", name: "North Korean Won" },
  KR: { code: "KRW", name: "South Korean Won" },
  KW: { code: "KWD", name: "Kuwaiti Dinar" },
  KY: { code: "KYD", name: "Cayman Islands Dollar" },
  KZ: { code: "KZT", name: "Kazakhstani Tenge" },
  LA: { code: "LAK", name: "Laotian Kip" },
  LB: { code: "LBP", name: "Lebanese Pound" },
  LC: { code: "XCD", name: "East Caribbean Dollar" },
  LI: { code: "CHF", name: "Swiss Franc" },
  LK: { code: "LKR", name: "Sri Lankan Rupee" },
  LR: { code: "LRD", name: "Liberian Dollar" },
  LS: { code: "LSL", name: "Lesotho Loti" },
  LT: { code: "EUR", name: "Euro" },
  LU: { code: "EUR", name: "Euro" },
  LV: { code: "EUR", name: "Euro" },
  LY: { code: "LYD", name: "Libyan Dinar" },
  MA: { code: "MAD", name: "Moroccan Dirham" },
  MC: { code: "EUR", name: "Euro" },
  MD: { code: "MDL", name: "Moldovan Leu" },
  ME: { code: "EUR", name: "Euro" },
  MF: { code: "EUR", name: "Euro" },
  MG: { code: "MGA", name: "Malagasy Ariary" },
  MH: { code: "USD", name: "United States Dollar" },
  MK: { code: "MKD", name: "Macedonian Denar" },
  ML: { code: "XOF", name: "CFA Franc BCEAO" },
  MM: { code: "MMK", name: "Myanmar Kyat" },
  MN: { code: "MNT", name: "Mongolian Tugrik" },
  MO: { code: "MOP", name: "Macanese Pataca" },
  MP: { code: "USD", name: "United States Dollar" },
  MQ: { code: "EUR", name: "Euro" },
  MR: { code: "MRU", name: "Mauritanian Ouguiya" },
  MS: { code: "XCD", name: "East Caribbean Dollar" },
  MT: { code: "EUR", name: "Euro" },
  MU: { code: "MUR", name: "Mauritian Rupee" },
  MV: { code: "MVR", name: "Maldivian Rufiyaa" },
  MW: { code: "MWK", name: "Malawian Kwacha" },
  MX: { code: "MXN", name: "Mexican Peso" },
  MY: { code: "MYR", name: "Malaysian Ringgit" },
  MZ: { code: "MZN", name: "Mozambican Metical" },
  NA: { code: "NAD", name: "Namibian Dollar" },
  NC: { code: "XPF", name: "CFP Franc" },
  NE: { code: "XOF", name: "CFA Franc BCEAO" },
  NF: { code: "AUD", name: "Australian Dollar" },
  NG: { code: "NGN", name: "Nigerian Naira" },
  NI: { code: "NIO", name: "Nicaraguan Córdoba" },
  NL: { code: "EUR", name: "Euro" },
  NO: { code: "NOK", name: "Norwegian Krone" },
  NP: { code: "NPR", name: "Nepalese Rupee" },
  NR: { code: "AUD", name: "Australian Dollar" },
  NU: { code: "NZD", name: "New Zealand Dollar" },
  NZ: { code: "NZD", name: "New Zealand Dollar" },
  OM: { code: "OMR", name: "Omani Rial" },
  PA: { code: "PAB", name: "Panamanian Balboa" },
  PE: { code: "PEN", name: "Peruvian Nuevo Sol" },
  PF: { code: "XPF", name: "CFP Franc" },
  PG: { code: "PGK", name: "Papua New Guinean Kina" },
  PH: { code: "PHP", name: "Philippine Peso" },
  PK: { code: "PKR", name: "Pakistani Rupee" },
  PL: { code: "PLN", name: "Polish Złoty" },
  PM: { code: "EUR", name: "Euro" },
  PN: { code: "NZD", name: "New Zealand Dollar" },
  PR: { code: "USD", name: "United States Dollar" },
  PS: { code: "ILS", name: "Israeli New Shekel" },
  PT: { code: "EUR", name: "Euro" },
  PW: { code: "USD", name: "United States Dollar" },
  PY: { code: "PYG", name: "Paraguayan Guarani" },
  QA: { code: "QAR", name: "Qatari Rial" },
  RE: { code: "EUR", name: "Euro" },
  RO: { code: "RON", name: "Romanian Leu" },
  RS: { code: "RSD", name: "Serbian Dinar" },
  RU: { code: "RUB", name: "Russian Ruble" },
  RW: { code: "RWF", name: "Rwandan Franc" },
  SA: { code: "SAR", name: "Saudi Riyal" },
  SB: { code: "SBD", name: "Solomon Islands Dollar" },
  SC: { code: "SCR", name: "Seychellois Rupee" },
  SD: { code: "SDG", name: "Sudanese Pound" },
  SE: { code: "SEK", name: "Swedish Krona" },
  SG: { code: "SGD", name: "Singapore Dollar" },
  SH: { code: "SHP", name: "Saint Helena Pound" },
  SI: { code: "EUR", name: "Euro" },
  SJ: { code: "NOK", name: "Norwegian Krone" },
  SK: { code: "EUR", name: "Euro" },
  SL: { code: "SLL", name: "Sierra Leonean Leone" },
  SM: { code: "EUR", name: "Euro" },
  SN: { code: "XOF", name: "CFA Franc BCEAO" },
  SO: { code: "SOS", name: "Somali Shilling" },
  SR: { code: "SRD", name: "Surinamese Dollar" },
  SS: { code: "SSP", name: "South Sudanese Pound" },
  ST: { code: "STN", name: "São Tomé and Príncipe Dobra" },
  SV: { code: "USD", name: "United States Dollar" },
  SX: { code: "ANG", name: "Netherlands Antillean Guilder" },
  SY: { code: "SYP", name: "Syrian Pound" },
  SZ: { code: "SZL", name: "Swazi Lilangeni" },
  TC: { code: "USD", name: "United States Dollar" },
  TD: { code: "XAF", name: "CFA Franc BEAC" },
  TF: { code: "EUR", name: "Euro" },
  TG: { code: "XOF", name: "CFA Franc BCEAO" },
  TH: { code: "THB", name: "Thai Baht" },
  TJ: { code: "TJS", name: "Tajikistani Somoni" },
  TK: { code: "NZD", name: "New Zealand Dollar" },
  TL: { code: "USD", name: "United States Dollar" },
  TM: { code: "TMT", name: "Turkmenistani Manat" },
  TN: { code: "TND", name: "Tunisian Dinar" },
  TO: { code: "TOP", name: "Tongan Pa'anga" },
  TR: { code: "TRY", name: "Turkish Lira" },
  TT: { code: "TTD", name: "Trinidad and Tobago Dollar" },
  TV: { code: "AUD", name: "Australian Dollar" },
  TW: { code: "TWD", name: "New Taiwan Dollar" },
  TZ: { code: "TZS", name: "Tanzanian Shilling" },
  UA: { code: "UAH", name: "Ukrainian Hryvnia" },
  UG: { code: "UGX", name: "Ugandan Shilling" },
  UM: { code: "USD", name: "United States Dollar" },
  US: { code: "USD", name: "United States Dollar" },
  UY: { code: "UYU", name: "Uruguayan Peso" },
  UZ: { code: "UZS", name: "Uzbekistan Som" },
  VA: { code: "EUR", name: "Euro" },
  VC: { code: "XCD", name: "East Caribbean Dollar" },
  VE: { code: "VES", name: "Venezuelan Bolívar" },
  VG: { code: "USD", name: "United States Dollar" },
  VI: { code: "USD", name: "United States Dollar" },
  VN: { code: "VND", name: "Vietnamese Đồng" },
  VU: { code: "VUV", name: "Vanuatu Vatu" },
  WF: { code: "XPF", name: "CFP Franc" },
  WS: { code: "WST", name: "Samoan Tala" },
  YE: { code: "YER", name: "Yemeni Rial" },
  YT: { code: "EUR", name: "Euro" },
  ZA: { code: "ZAR", name: "South African Rand" },
  ZM: { code: "ZMW", name: "Zambian Kwacha" },
  ZW: { code: "ZWL", name: "Zimbabwean Dollar" },
};

const PHONE_PREFIXES = {
  AF: "93",
  AL: "355",
  DZ: "213",
  AS: "1-684",
  AD: "376",
  AO: "244",
  AI: "1-264",
  AQ: "672",
  AG: "1-268",
  AR: "54",
  AM: "374",
  AW: "297",
  AU: "61",
  AT: "43",
  AZ: "994",
  BS: "1-242",
  BH: "973",
  BD: "880",
  BB: "1-246",
  BY: "375",
  BE: "32",
  BZ: "501",
  BJ: "229",
  BM: "1-441",
  BT: "975",
  BO: "591",
  BA: "387",
  BW: "267",
  BR: "55",
  IO: "246",
  VG: "1-284",
  BN: "673",
  BG: "359",
  BF: "226",
  BI: "257",
  KH: "855",
  CM: "237",
  CA: "1",
  CV: "238",
  KY: "1-345",
  CF: "236",
  TD: "235",
  CL: "56",
  CN: "86",
  CX: "61",
  CC: "61",
  CO: "57",
  KM: "269",
  CK: "682",
  CR: "506",
  HR: "385",
  CU: "53",
  CW: "599",
  CY: "357",
  CZ: "420",
  CD: "243",
  DK: "45",
  DJ: "253",
  DM: "1-767",
  DO: "1-809, 1-829, 1-849",
  TL: "670",
  EC: "593",
  EG: "20",
  SV: "503",
  GQ: "240",
  ER: "291",
  EE: "372",
  ET: "251",
  FK: "500",
  FO: "298",
  FJ: "679",
  FI: "358",
  FR: "33",
  PF: "689",
  GA: "241",
  GM: "220",
  GE: "995",
  DE: "49",
  GH: "233",
  GI: "350",
  GR: "30",
  GL: "299",
  GD: "1-473",
  GU: "1-671",
  GT: "502",
  GG: "44-1481",
  GN: "224",
  GW: "245",
  GY: "592",
  HT: "509",
  HN: "504",
  HK: "852",
  HU: "36",
  IS: "354",
  IN: "91",
  ID: "62",
  IR: "98",
  IQ: "964",
  IE: "353",
  IM: "44-1624",
  IL: "972",
  IT: "39",
  CI: "225",
  JM: "1-876",
  JP: "81",
  JE: "44-1534",
  JO: "962",
  KZ: "7",
  KE: "254",
  KI: "686",
  XK: "383",
  KW: "965",
  KG: "996",
  LA: "856",
  LV: "371",
  LB: "961",
  LS: "266",
  LR: "231",
  LY: "218",
  LI: "423",
  LT: "370",
  LU: "352",
  MO: "853",
  MK: "389",
  MG: "261",
  MW: "265",
  MY: "60",
  MV: "960",
  ML: "223",
  MT: "356",
  MH: "692",
  MR: "222",
  MU: "230",
  YT: "262",
  MX: "52",
  FM: "691",
  MD: "373",
  MC: "377",
  MN: "976",
  ME: "382",
  MS: "1-664",
  MA: "212",
  MZ: "258",
  MM: "95",
  NA: "264",
  NR: "674",
  NP: "977",
  NL: "31",
  AN: "599",
  NC: "687",
  NZ: "64",
  NI: "505",
  NE: "227",
  NG: "234",
  NU: "683",
  KP: "850",
  MP: "1-670",
  NO: "47",
  OM: "968",
  PK: "92",
  PW: "680",
  PS: "970",
  PA: "507",
  PG: "675",
  PY: "595",
  PE: "51",
  PH: "63",
  PN: "64",
  PL: "48",
  PT: "351",
  PR: "1-787, 1-939",
  QA: "974",
  CG: "242",
  RE: "262",
  RO: "40",
  RU: "7",
  RW: "250",
  BL: "590",
  SH: "290",
  KN: "1-869",
  LC: "1-758",
  MF: "590",
  PM: "508",
  VC: "1-784",
  WS: "685",
  SM: "378",
  ST: "239",
  SA: "966",
  SN: "221",
  RS: "381",
  SC: "248",
  SL: "232",
  SG: "65",
  SX: "1-721",
  SK: "421",
  SI: "386",
  SB: "677",
  SO: "252",
  ZA: "27",
  KR: "82",
  SS: "211",
  ES: "34",
  LK: "94",
  SD: "249",
  SR: "597",
  SJ: "47",
  SZ: "268",
  SE: "46",
  CH: "41",
  SY: "963",
  TW: "886",
  TJ: "992",
  TZ: "255",
  TH: "66",
  TG: "228",
  TK: "690",
  TO: "676",
  TT: "1-868",
  TN: "216",
  TR: "90",
  TM: "993",
  TC: "1-649",
  TV: "688",
  VI: "1-340",
  UG: "256",
  UA: "380",
  AE: "971",
  GB: "44",
  US: "1",
  UY: "598",
  UZ: "998",
  VU: "678",
  VA: "379",
  VE: "58",
  VN: "84",
  WF: "681",
  EH: "212",
  YE: "967",
  ZM: "260",
  ZW: "263",
};

const THIRD_PARTY_CHARGES = {
  card: 0.03,
  bankAccount: 0.015,
};

const CARD_BRAND_IMG = {
  visa,
  mastercard,
};

export {
  SITE_PADDING_X,
  USER_COUNTRIES,
  TRANSFER_COUNTRIES,
  LANGUAGES,
  CURRENCIES,
  PHONE_PREFIXES,
  THIRD_PARTY_CHARGES,
  CARD_BRAND_IMG,
};
